const Q=[
{c:"Ch.1 Parichay",q:'MP ka sthaapana kab hua?',o:['15 August 1947','26 January 1950','1 November 1956','1 November 1960'],a:2,n:'MP formed on 1 November 1956 through State Reorganisation Act.'},
{c:"Ch.1 Parichay",q:'MP ki rajdhani Bhopal se pehle kiska hissa tha?',o:['Vidisha district','Ujjain district','Sehore district','Raisen district'],a:2,n:'Bhopal was a tehsil of Sehore district before becoming capital in 1956.'},
{c:"Ch.1 Parichay",q:'MP ka sabse bada shahar kaun sa hai?',o:['Bhopal','Gwalior','Indore','Jabalpur'],a:2,n:'Indore is the largest city of MP by population and commerce.'},
{c:"Ch.1 Parichay",q:'MP ki rajbhaasha kya hai?',o:['Sanskrit','Urdu','Hindi','Bundeli'],a:2,n:'Hindi is the official language of MP.'},
{c:"Ch.1 Parichay",q:'MP ka ksheatrafal kitna hai?',o:['3,08,446 sq km','3,08,211 sq km','3,08,252 sq km','3,08,000 sq km'],a:2,n:"3,08,252 sq km — 9.38% of India's total area."},
{c:"Ch.1 Parichay",q:'Ksheatrafal mein MP ka India mein kaun sa sthan hai?',o:['1st','2nd','3rd','4th'],a:1,n:'2nd largest state in India after Rajasthan.'},
{c:"Ch.1 Parichay",q:'India ki total area mein MP ka kitna pratishat hai?',o:['7.38%','8.38%','9.38%','10.38%'],a:2,n:"MP covers 9.38% of India's total geographical area."},
{c:"Ch.1 Parichay",q:'Undivided MP (Chhattisgarh se pehle) ka ksheatrafal kitna tha?',o:['3,08,252 sq km','3,50,000 sq km','4,43,444 sq km','4,00,000 sq km'],a:2,n:'Undivided MP (before 2000) = 4,43,444 sq km — was 1st largest.'},
{c:"Ch.1 Parichay",q:'MP ke uttar mein kaun sa rajya hai?',o:['Rajasthan','Gujarat','Uttar Pradesh','Chhattisgarh'],a:2,n:'North: Uttar Pradesh.'},
{c:"Ch.1 Parichay",q:'MP ke dakshin mein kaun sa rajya hai?',o:['Gujarat','Maharashtra','Karnataka','Andhra Pradesh'],a:1,n:'South: Maharashtra.'},
{c:"Ch.1 Parichay",q:'MP ke paschim mein kaun se rajya hain?',o:['UP & Rajasthan','Maharashtra & Gujarat','Gujarat & Rajasthan','Rajasthan & UP'],a:2,n:'West: Gujarat & Rajasthan (Northwest).'},
{c:"Ch.1 Parichay",q:'MP ke purv mein kaun sa rajya hai?',o:['Uttar Pradesh','Chhattisgarh','Maharashtra','Rajasthan'],a:1,n:'East: Chhattisgarh (also NE).'},
{c:"Ch.1 Parichay",q:'MP ke sabse lambi seema kis rajya ke saath hai?',o:['Chhattisgarh','Maharashtra','Rajasthan','Uttar Pradesh'],a:3,n:'Uttar Pradesh — longest shared border with MP.'},
{c:"Ch.1 Parichay",q:'MP ke sabse chhhoti seema kis rajya ke saath hai?',o:['Rajasthan','Gujarat','Maharashtra','UP'],a:1,n:'Gujarat — shortest shared border with MP.'},
{c:"Ch.1 Parichay",q:'MP kitne rajyon ki seeaon se ghira hai?',o:['4','5','6','7'],a:1,n:'5 states: UP, Chhattisgarh, Maharashtra, Gujarat, Rajasthan.'},
{c:"Ch.1 Parichay",q:'MP Bhuaaveshit (Landlocked) rajya hai — iska matlab kya hai?',o:['Koi nadi nahin','Koi samudra tatiya nahin','Koi pahad nahin','Koi jungle nahin'],a:1,n:'MP is completely landlocked — no coastline, no international border.'},
{c:"Ch.1 Parichay",q:'MP ki N–S (uttar-dakshin) lambai kitni hai?',o:['870 km','605 km','996 km','1127 km'],a:1,n:'N–S extent = 605 km. E–W = 870 km.'},
{c:"Ch.1 Parichay",q:'MP ki E–W (purv-paschim) lambai kitni hai?',o:['605 km','870 km','996 km','724 km'],a:1,n:'E–W extent = 870 km. N–S = 605 km.'},
{c:"Ch.1 Parichay",q:'Undivided MP ki N–S lambai kitni thi?',o:['605 km','870 km','1,127 km','996 km'],a:2,n:'Undivided MP N–S = 1,127 km. Present MP = 605 km.'},
{c:"Ch.1 Parichay",q:'Undivided MP ki E–W lambai kitni thi?',o:['870 km','605 km','996 km','1,127 km'],a:2,n:'Undivided MP E–W = 996 km. Present MP = 870 km.'},
{c:"Ch.1 Parichay",q:'MP ka pratham rajyapal kaun tha?',o:['Fazal Ali','Ravi Shankar Shukla','B.P. Sitaramaiya','Hridaynath Kunzru'],a:2,n:'B.P. Sitaramaiya was 1st Governor of MP (1956).'},
{c:"Ch.1 Parichay",q:'MP ka pratham mukhyamantri kaun tha?',o:['Kailash Nath Katju','B.P. Sitaramaiya','D.P. Mishra','Ravi Shankar Shukla'],a:3,n:'Ravi Shankar Shukla was 1st CM of MP (1956).'},
{c:"Ch.1 Parichay",q:'MP ka uchcha nyayalay kahan hai?',o:['Bhopal','Indore','Gwalior','Jabalpur'],a:3,n:'MP High Court main bench is at Jabalpur.'},
{c:"Ch.1 Parichay",q:'MP High Court ke khandpeeth (benches) kahan hain?',o:['Ujjain & Rewa','Indore & Gwalior','Sagar & Jabalpur','Bhopal & Indore'],a:1,n:'MP High Court benches at Indore & Gwalior. Main: Jabalpur.'},
{c:"Ch.1 Parichay",q:'MP kis golaardh mein sthit hai?',o:['Southern + Eastern','Northern + Western','Northern + Eastern','Southern + Western'],a:2,n:'Northern Hemisphere (latitude) + Eastern Hemisphere (longitude).'},
{c:"Ch.1 Parichay",q:'MP ki rajbhaasha ke alaava aur kaun si bhashaen boli jaati hain?',o:['Gujarati & Marathi','Bundeli, Bagheli, Malvi, Nimadi, Gondi, Urdu','Tamil & Telugu','Punjabi & Bengali'],a:1,n:'Urdu, Bundeli, Bagheli, Malvi, Nimadi, Gondi, Korku are also spoken.'},
{c:"Ch.1 Parichay",q:"MP ko 'Bharat ka Hridaya' kyun kaha jaata hai?",o:['Sabse zyada population','Geographically India ke centre mein','Sabse bada rajya','Sabse purana rajya'],a:1,n:'MP is geographically at the centre of India, bordered by 5 states.'},
{c:"Ch.1 Parichay",q:'Kark Rekha (Tropic of Cancer) MP ke kitne jilon se guzarti hai?',o:['10','12','14','16'],a:2,n:'14 districts from Ratlam (west) to Shahdol (east).'},
{c:"Ch.1 Parichay",q:'MP mein kaun si kark rekha ki paschimi sima ka pehla jila hai?',o:['Ujjain','Sehore','Ratlam','Agar Malwa'],a:2,n:'Ratlam is the westernmost district through which Tropic of Cancer passes.'},
{c:"Ch.1 Parichay",q:'Kitne madhyavarti (interior) jile kisi doosre rajya se seema nahin bante?',o:['14','16','18','20'],a:2,n:'18 districts share no border with any other state.'},
{c:"Ch.1 Parichay",q:'Undivided MP ka area rank India mein kaun sa tha?',o:['1st','2nd','3rd','4th'],a:0,n:'Undivided MP (before CG separation) was 1st largest. Present MP is 2nd.',u:'Undivided MP was 1st; Present MP is 2nd largest state.'},
{c:"Ch.1 Parichay",q:'MP mein kitni pramukh bhashaayen boli jaati hain?',o:['3','5','7+','10+'],a:2,n:'7+ languages: Hindi, Urdu, Bundeli, Bagheli, Malvi, Nimadi, Gondi, Korku.'},
{c:"Ch.2 Geo Position",q:'Present MP ki latitude kya hai?',o:["17°46'N–26°30'N","21°6'N–26°30'N","21°4'N–26°30'N","20°6'N–26°30'N"],a:1,n:"Present MP latitude: 21°6'N–26°30'N. Undivided was 17°46'N.",u:"Undivided MP was 17°46'N — MCQ trap!"},
{c:"Ch.2 Geo Position",q:'Vibhajit (undivided) MP ki latitude kya thi?',o:["21°6'N–26°30'N","17°46'N–26°30'N","15°N–26°30'N","18°N–26°30'N"],a:1,n:"Undivided MP latitude: 17°46'N–26°30'N (Chhattisgarh south included)."},
{c:"Ch.2 Geo Position",q:'Present MP ki longitude kya hai?',o:["74°9'E–84°51'E","74°9'E–82°48'E",'72°E–82°E','74°E–84°E'],a:1,n:"Present MP longitude: 74°9'E–82°48'E."},
{c:"Ch.2 Geo Position",q:'Vibhajit (undivided) MP ki longitude kya thi?',o:["74°9'E–82°48'E","74°9'E–84°51'E",'72°E–86°E','74°E–82°E'],a:1,n:"Undivided MP longitude: 74°9'E–84°51'E."},
{c:"Ch.2 Geo Position",q:'Vibhajit (undivided) MP ka ksheatrafal kitna tha?',o:['3,08,252 sq km','4,43,444 sq km','4,00,000 sq km','3,50,000 sq km'],a:1,n:'Undivided MP = 4,43,444 sq km.'},
{c:"Ch.2 Geo Position",q:'Kark Rekha (Tropic of Cancer) MP ke kitne jilon se guzarti hai?',o:['12','13','14','15'],a:2,n:'14 districts from Ratlam (west) to Shahdol (east).'},
{c:"Ch.2 Geo Position",q:'Kark Rekha ke pashchimatam jila kaun sa hai?',o:['Ujjain','Sehore','Ratlam','Agar Malwa'],a:2,n:'Ratlam is the westernmost district of the Tropic of Cancer belt in MP.'},
{c:"Ch.2 Geo Position",q:'Kark Rekha ke poorvatam jila kaun sa hai?',o:['Jabalpur','Umaria','Shahdol','Katni'],a:2,n:'Shahdol is the easternmost district through which Tropic of Cancer passes.'},
{c:"Ch.2 Geo Position",q:'Kitne madhyavarti (interior) jile kisi rajya ki seema nahin bante?',o:['14','16','18','20'],a:2,n:'18 districts of MP share no border with any other state.'},
{c:"Ch.2 Geo Position",q:'Area rank ke anusaar undivided MP ka India mein kaun sa sthan tha?',o:['1st','2nd','3rd','4th'],a:0,n:'Undivided MP was 1st largest state. Present MP is 2nd.',u:'Undivided = 1st; Present = 2nd.'},
{c:"Ch.2 Geo Position",q:'MP kisne golaardh mein sthit hai?',o:['Southern + Eastern','Northern + Western','Northern + Eastern','Southern + Western'],a:2,n:'Northern Hemisphere (latitude) + Eastern Hemisphere (longitude).'},
{c:"Ch.2 Geo Position",q:'MP ki latitude ki uttar seema kya hai?',o:["21°6'N",'24°N',"26°30'N",'28°N'],a:2,n:"Northern boundary of present MP = 26°30'N latitude."},
{c:"Ch.2 Geo Position",q:'MP ki latitude ki dakshin seema kya hai?',o:["21°6'N",'18°N',"17°46'N",'23°N'],a:0,n:"Southern boundary of present MP = 21°6'N latitude."},
{c:"Ch.2 Geo Position",q:'Present MP ki longitude ki paschim seema kya hai?',o:['72°E',"74°9'E",'76°E','78°E'],a:1,n:"Western boundary of present MP longitude = 74°9'E."},
{c:"Ch.2 Geo Position",q:'Present MP ki longitude ki purv seema kya hai?',o:['80°E',"82°48'E","84°51'E",'86°E'],a:1,n:"Eastern boundary of present MP longitude = 82°48'E."},
{c:"Ch.3 Extreme Districts",q:'MP ka uttaratam (northernmost) jila kaun sa hai?',o:['Bhind','Morena','Sheopur','Gwalior'],a:1,n:'Morena = northernmost district. Chambal division.'},
{c:"Ch.3 Extreme Districts",q:'MP ka dakshinatam (southernmost) jila kaun sa hai?',o:['Khandwa','Betul','Burhanpur','Harda'],a:2,n:'Burhanpur = southernmost. Borders Maharashtra. Mumtaz Mahal died here (1631).'},
{c:"Ch.3 Extreme Districts",q:'MP ka pashchimatam (westernmost) jila kaun sa hai?',o:['Jhabua','Dhar','Barwani','Alirajpur'],a:3,n:'Alirajpur = westernmost. Borders Gujarat & Rajasthan. Highest ST% in MP.'},
{c:"Ch.3 Extreme Districts",q:'MP ka poorvatam (easternmost) jila kaun sa hai?',o:['Sidhi','Umaria','Singrauli','Shahdol'],a:2,n:'Singrauli = easternmost. 50th district (2008). Coal Capital.'},
{c:"Ch.3 Extreme Districts",q:'Morena kis sambhag mein hai?',o:['Gwalior','Chambal','Bhopal','Indore'],a:1,n:'Morena is in Chambal sambhag (Morena, Bhind, Sheopur).'},
{c:"Ch.3 Extreme Districts",q:'Burhanpur mein kaun si nadi behti hai?',o:['Narmada','Chambal','Tapti','Betwa'],a:2,n:'Tapti river flows through Burhanpur — southernmost district.'},
{c:"Ch.3 Extreme Districts",q:'Mumtaz Mahal ka nidhan kahan hua tha?',o:['Bhopal','Agra','Burhanpur','Surat'],a:2,n:'Mumtaz Mahal (Taj Mahal inspiration) died in Burhanpur in 1631.'},
{c:"Ch.3 Extreme Districts",q:'Burhanpur kis sambhag mein hai?',o:['Narmadapuram','Jabalpur','Indore','Bhopal'],a:2,n:'Burhanpur is in Indore sambhag.'},
{c:"Ch.3 Extreme Districts",q:'Alirajpur mein sabse adhik kaun si janjaati hai?',o:['Gond','Baiga','Bhil','Korku'],a:2,n:'Bhil tribe is dominant in Alirajpur. Highest ST% district in MP.'},
{c:"Ch.3 Extreme Districts",q:'Alirajpur kis sambhag mein hai?',o:['Narmadapuram','Jabalpur','Indore','Bhopal'],a:2,n:'Alirajpur is in Indore sambhag.'},
{c:"Ch.3 Extreme Districts",q:'Singrauli kaunse number ka jila bana tha?',o:['48th','49th','50th','51st'],a:2,n:'Singrauli = 50th district of MP (24 May 2008, from Sidhi).'},
{c:"Ch.3 Extreme Districts",q:'Singrauli kahan se bana tha?',o:['Rewa','Shahdol','Sidhi','Umaria'],a:2,n:'Singrauli was carved from Sidhi district on 24 May 2008.'},
{c:"Ch.3 Extreme Districts",q:'Singrauli kis rajya ki bhi seema se laga hai (MP ke alaava)?',o:['Rajasthan & Gujarat','UP & Chhattisgarh','Maharashtra only','Bihar & UP'],a:1,n:'Singrauli borders both UP and Chhattisgarh.'},
{c:"Ch.3 Extreme Districts",q:'Asia ka sabse mota coal seam kahan hai?',o:['Sonbhadra UP','Dhanbad Jharkhand','Singrauli MP','Korba CG'],a:2,n:'Singrauli coalfield has the thickest coal seam in Asia.'},
{c:"Ch.3 Extreme Districts",q:'Dakshinatam jila Burhanpur kis sambhag mein aata hai?',o:['Jabalpur','Narmadapuram','Indore','Sagar'],a:2,n:'Burhanpur is in Indore division.'},
{c:"Ch.4 Population",q:'Census 2011 mein MP ki kul janasankhya kitni thi?',o:['6.52 Crore','7.26 Crore','8.10 Crore','5.50 Crore'],a:1,n:'7,26,26,809 (7.26 Crore) — Census 2011.'},
{c:"Ch.4 Population",q:'MP ki janasankhya India mein kaun se sthan par hai?',o:['2nd','3rd','4th','5th'],a:3,n:'5th most populous state (since 2014).'},
{c:"Ch.4 Population",q:'MP mein ST janasankhya ka India mein rank kaun sa hai?',o:['2nd','3rd','1st','4th'],a:2,n:'MP = 1st rank in ST population in India.'},
{c:"Ch.4 Population",q:'MP mein ling anupaat (sex ratio) Census 2011 mein kya tha?',o:['921','931','941','951'],a:1,n:'931 females per 1,000 males. Rank: 20th nationally / 18th among states.'},
{c:"Ch.4 Population",q:'0–6 ayu varg mein MP ka shishu ling anupaat kya tha?',o:['908','918','928','938'],a:1,n:'918 per 1,000 males — Shishu Ling Anupaat.'},
{c:"Ch.4 Population",q:'MP mein janasankhya ghanatv Census 2011 mein kya tha?',o:['186','206','226','236'],a:3,n:'236 persons per sq km.'},
{c:"Ch.4 Population",q:'MP mein saksharata dar Census 2011 mein kya thi?',o:['64.11%','69.32%','73.00%','75.00%'],a:1,n:'69.32% — 28th nationally, 21st among states.'},
{c:"Ch.4 Population",q:'MP mein purush saksharata dar Census 2011 mein kya thi?',o:['73.25%','75.50%','78.73%','80.12%'],a:2,n:'Male literacy = 78.73%.'},
{c:"Ch.4 Population",q:'MP mein mahila saksharata dar Census 2011 mein kya thi?',o:['54.16%','59.24%','62.37%','65.50%'],a:1,n:'Female literacy = 59.24%.'},
{c:"Ch.4 Population",q:'Saksharata mein MP ki rank sirf rajyon mein kya hai?',o:['15th','21st','25th','28th'],a:1,n:'Literacy rank: 28th overall / 21st among states.'},
{c:"Ch.4 Population",q:'Saksharata mein MP ki rank all India mein kya hai?',o:['21st','25th','28th','30th'],a:2,n:'28th overall (all India) in literacy.'},
{c:"Ch.4 Population",q:'MP mein SC janasankhya ka pratishat kitna hai?',o:['12.6%','15.6%','18.6%','21.6%'],a:1,n:'SC population = 15.6%.'},
{c:"Ch.4 Population",q:'MP mein ST janasankhya ka pratishat kitna hai?',o:['15.1%','18.1%','21.1%','24.1%'],a:2,n:'ST population = 21.1% (1st rank in India).'},
{c:"Ch.4 Population",q:'MP mein shahri (urban) janasankhya ka pratishat kitna hai?',o:['22.63%','25.63%','27.63%','30.63%'],a:2,n:'Urban population = 27.63%.'},
{c:"Ch.4 Population",q:'MP mein gramin (rural) janasankhya ka pratishat kitna hai?',o:['65.37%','70.37%','72.37%','75.37%'],a:2,n:'Rural population = 72.37%.'},
{c:"Ch.4 Population",q:'MP mein sabse adhik aabaadi wala jila kaun sa hai?',o:['Bhopal','Gwalior','Indore','Jabalpur'],a:2,n:'Indore = most populous district (32.76 lakh, Census 2011).'},
{c:"Ch.4 Population",q:'MP mein sabse kam aabaadi wala jila kaun sa hai?',o:['Datia','Niwari','Harda','Sheopur'],a:2,n:'Harda = least populous (5.70 lakh, Census 2011).'},
{c:"Ch.4 Population",q:'MP mein sabse badi janjaati (tribe) kaun si hai?',o:['Gond','Bhil','Korku','Sahariya'],a:1,n:'Bhil = largest tribe (37.7% of ST). Gond = 2nd.'},
{c:"Ch.4 Population",q:'MP mein teen PVTGs (Primitive Vulnerable Tribal Groups) kaun si hain?',o:['Bhil, Gond, Korku','Bhariya, Baiga, Sahariya','Bhil, Baiga, Halba','Sahariya, Korku, Mawasi'],a:1,n:"MP's 3 PVTGs: Bhariya, Baiga, Sahariya."},
{c:"Ch.4 Population",q:'MP ki anumaanik 2026 mein janasankhya kitni hai?',o:['7.26 Crore','8.10 Crore','~8.93–8.97 Crore','9.50 Crore'],a:2,n:'~8.93–8.97 Crore (projection — Census 2021 deferred).'},
{c:"Ch.4 Population",q:'Census 2021 kyon nahin hua?',o:['Budget shortage','COVID-19 pandemic','Political reasons','Technical issues'],a:1,n:'Census 2021 was deferred due to COVID-19 pandemic.'},
{c:"Ch.4 Population",q:'Ling anupaat rank MP ka sirf rajyon mein kya hai?',o:['15th','18th','20th','25th'],a:1,n:'Sex Ratio rank: 20th overall / 18th among states.'},
{c:"Ch.4 Population",q:'Purush janasankhya Census 2011 mein kitni thi?',o:['3.50 Crore','3.76 Crore','4.00 Crore','4.26 Crore'],a:1,n:'Male population = 3,76,12,306 (3.76 Crore).'},
{c:"Ch.4 Population",q:'Mahila janasankhya Census 2011 mein kitni thi?',o:['3.26 Crore','3.50 Crore','3.76 Crore','4.00 Crore'],a:1,n:'Female population = 3,50,14,503 (3.50 Crore).'},
{c:"Ch.4 Population",q:'MP mein Gond tribe ka ST population mein kaun sa rank hai?',o:['1st','2nd','3rd','4th'],a:1,n:'Gond = 2nd largest tribe in MP. Bhil = 1st.'},
{c:"Ch.5 Rajya Prateek",q:'Rajya Chinh mein sabse bahar kitne Stupa hain?',o:['12','18','24','36'],a:2,n:'24 Stupa figures at the outermost ring of MP emblem (Buddhist heritage).'},
{c:"Ch.5 Rajya Prateek",q:'Rajya Chinh ke kendriya vritt mein kya inscribed hai?',o:['Jai Hind','Satyamev Jayate + MP Shaasan','MP Rajya','Bharat Mata ki Jai'],a:1,n:"'MP Shaasan' + 'Satyamev Jayate' inscribed in the circle."},
{c:"Ch.5 Rajya Prateek",q:'Rajya Chinh mein Ashoka Stambh ke saath kaun sa vriksha dikhaya gaya hai?',o:['Neem','Peepal','Bargad','Teak'],a:2,n:'Bargad (Banyan) shown with Ashoka Lion in centre of MP emblem.'},
{c:"Ch.5 Rajya Prateek",q:'Rajya Chinh mein kaunsi faslein dikhaayi gayi hain?',o:['Soyabean & Cotton','Wheat (Gehu) & Paddy (Dhan)','Sugarcane & Rice','Bajra & Jowar'],a:1,n:'Wheat and Paddy stalks are shown in MP State Emblem.'},
{c:"Ch.5 Rajya Prateek",q:'Rajya Chinh mein 24 Stupas kiska pratik hain?',o:['Mahabharat ke yodha','Sanchi ka Buddhist heritage','24 rajya','24 jile'],a:1,n:"24 Stupas represent Sanchi's Buddhist heritage."},
{c:"Ch.5 Rajya Prateek",q:'Rajya Pashu (state animal) kaun sa hai?',o:['Sher','Barasingha','Cheetah','Nilgai'],a:1,n:'Barasingha (Swamp Deer) is the state animal of MP.'},
{c:"Ch.5 Rajya Prateek",q:'Barasingha ka scientific naam kya hai?',o:['Cervus elaphus','Rucervus duvaucelii','Axis axis','Boselaphus tragocamelus'],a:1,n:'Rucervus duvaucelii (also written Cervus duvaucelii).'},
{c:"Ch.5 Rajya Prateek",q:'Barasingha ki kaunsi species Kanha mein payi jaati hai?',o:['Rucervus species','Braderi species','Hangul species','Sangai species'],a:1,n:'Braderi species (Hard Ground Barasingha) — found ONLY at Kanha.'},
{c:"Ch.5 Rajya Prateek",q:'Barasingha ka mukhy kshetra kaun sa national park hai?',o:['Bandhavgarh NP','Satpura NP','Kanha Kisli NP Mandla','Panna TR'],a:2,n:'Kanha Kisli National Park, Mandla — primary habitat.'},
{c:"Ch.5 Rajya Prateek",q:"Barasingha ke naam mein 'Baara' ka kya matlab hai?",o:['8 antlers','10 antlers','12 antlers','16 antlers'],a:2,n:'Baara = 12. Barasingha = 12-tined deer.'},
{c:"Ch.5 Rajya Prateek",q:'Barasingha ko kahan extinction se bachaya gaya?',o:['Bandhavgarh','Panna TR','Kanha Kisli NP Mandla','Satpura NP'],a:2,n:'Saved from ~66 animals at Kanha. Now 900+.'},
{c:"Ch.5 Rajya Prateek",q:'Barasingha ki IUCN status kya hai?',o:['Endangered','Critically Endangered','Vulnerable','Least Concern'],a:2,n:'Barasingha = Vulnerable (IUCN Red List).'},
{c:"Ch.5 Rajya Prateek",q:'Rajya Pakshi (state bird) kaun sa hai?',o:['Mor (Peacock)','Dodhraj / Shah Bulbul','Tota','Koyal'],a:1,n:'Dodhraj / Shah Bulbul (Paradise Flycatcher).'},
{c:"Ch.5 Rajya Prateek",q:'Dodhraj ka scientific naam kya hai?',o:['Pycnonotus jocosus','Terpsiphone paradisi','Dendrocopos nanus','Motacilla alba'],a:1,n:'Terpsiphone paradisi (also Terfisphon paradisi).'},
{c:"Ch.5 Rajya Prateek",q:'Dodhraj ka mukhy kshetra kahan hai?',o:['Kanha NP','Pachmarhi','Selana & Sardarpur Sanctuaries','Bandhavgarh'],a:2,n:'NW MP — Selana Sanctuary (Ratlam) + Sardarpur Sanctuary (Dhar).'},
{c:"Ch.5 Rajya Prateek",q:'Dodhraj sabse adhik kahan paya jata hai?',o:['Baghelkhand','Bundelkhand','Malwa region','Chambal'],a:2,n:'Most found in Malwa region.'},
{c:"Ch.5 Rajya Prateek",q:'Selana Wildlife Sanctuary kahan hai?',o:['Dhar','Ratlam','Ujjain','Mandsaur'],a:1,n:'Selana Wildlife Sanctuary = Ratlam district.'},
{c:"Ch.5 Rajya Prateek",q:'Sardarpur Wildlife Sanctuary kahan hai?',o:['Dhar','Ratlam','Indore','Ujjain'],a:0,n:'Sardarpur Wildlife Sanctuary = Dhar district.'},
{c:"Ch.5 Rajya Prateek",q:'Rajya Vriksha (state tree) kaun sa hai?',o:['Neem','Peepal','Bargad (Banyan)','Teak'],a:2,n:'Bargad (Banyan Tree — Ficus benghalensis).'},
{c:"Ch.5 Rajya Prateek",q:'Rajya Vriksha Bargad ka scientific naam kya hai?',o:['Ficus religiosa','Ficus benghalensis','Ficus racemosa','Tectona grandis'],a:1,n:'Bargad = Ficus benghalensis.'},
{c:"Ch.5 Rajya Prateek",q:'Rajya Pushpa (state flower) kaun sa hai?',o:['Kamal','Safed Lily','Marigold','Rose'],a:1,n:'Safed Lily (White Lily — Lilium candidum).'},
{c:"Ch.5 Rajya Prateek",q:'Rajya Pushpa Safed Lily ka scientific naam kya hai?',o:['Lilium tigrinum','Lilium candidum','Nelumbo nucifera','Rosa indica'],a:1,n:'Safed Lily = Lilium candidum.'},
{c:"Ch.5 Rajya Prateek",q:'Rajya Machali (state fish) kaun si hai?',o:['Rohu','Catla','Mahasheer','Hilsa'],a:2,n:"Mahasheer (Tor putitora) — 'King of Freshwater Fish.'"},
{c:"Ch.5 Rajya Prateek",q:'Mahasheer ka scientific naam kya hai?',o:['Labeo rohita','Tor putitora','Catla catla','Hilsa ilisha'],a:1,n:'Mahasheer = Tor putitora.'},
{c:"Ch.5 Rajya Prateek",q:'Rajya Naatya (state drama) kaun sa hai?',o:['Lavani','Mach / Maach','Raas','Jhumair'],a:1,n:'Mach / Maach — state drama of MP.'},
{c:"Ch.5 Rajya Prateek",q:'Mach naatya ka mukhy kshetra kahan hai?',o:['Bundelkhand','Malwa region','Baghelkhand','Chambal'],a:1,n:'Mach = Malwa region (Ujjain, Indore, Ratlam area).'},
{c:"Ch.5 Rajya Prateek",q:'Mach naatya kab perform kiya jaata hai?',o:['Subah','Dopahar','Raat (night)','Shaam'],a:2,n:'Mach performed on raised wooden platform during night-long performances.'},
{c:"Ch.5 Rajya Prateek",q:'Mach naatya ke prasiddh kalaakaar kaun hain?',o:['Ravi Shankar & Ali Akbar','Ustad Gulab Bai & Banshilal','Tansen & Baiju Bawra','Kishore Kumar & Lata'],a:1,n:'Prominent Mach artists: Ustad Gulab Bai, Banshilal, Siddheshwar Sen, Ramchandra Kumat.'},
{c:"Ch.5 Rajya Prateek",q:'Rajya Khel (state sport) kaun sa hai?',o:['Kabaddi','Cricket','Malkhamb','Kushti'],a:2,n:'Malkhamb (Malakhamb).'},
{c:"Ch.5 Rajya Prateek",q:'Malkhamb kab rajya khel ghoshit hua?',o:['1 November 1981','26 January 1972','9 April 2013','15 August 2000'],a:2,n:'9 April 2013.',u:'NOT 1981. That was for Pashu/Pakshi/Vriksha/Pushpa.'},
{c:"Ch.5 Rajya Prateek",q:'Malkhamb Academy kahan hai?',o:['Bhopal','Indore','Gwalior','Ujjain'],a:3,n:'Malkhamb Academy = Ujjain.'},
{c:"Ch.5 Rajya Prateek",q:"Malkhamb mein 'Malla' ka matlab kya hai?",o:['King','Wrestler','Pole','Dance'],a:1,n:'Malla = wrestler, Khamb = pole.'},
{c:"Ch.5 Rajya Prateek",q:'Malkhamb ke kitne prakar hain?',o:['2','3','4','5'],a:1,n:'3 types: Pole Malkhamb, Rope Malkhamb, Hanging Malkhamb.'},
{c:"Ch.5 Rajya Prateek",q:'Rajya Fasal (state crop) kaun si hai?',o:['Gehu','Dhan','Soyabean','Cotton'],a:2,n:"Soyabean — India's #1 with 55–60% national production."},
{c:"Ch.5 Rajya Prateek",q:'MP rajya gaan ke lekhak kaun hain?',o:['Maithilisharan Gupta','Subhadra Kumari Chauhan','Mahesh Shri Srivastava','Harivansh Rai Bachchan'],a:2,n:"'Sukh ka daata sab ka saathi...' — Mahesh Shri Srivastava."},
{c:"Ch.5 Rajya Prateek",q:'Rajya prateek kab ghoshit kiye gaye?',o:['1 November 1956','1 November 1971','1 November 1981','1 November 1991'],a:2,n:'1 November 1981 = 25th foundation day.'},
{c:"Ch.5 Rajya Prateek",q:'Bundelkhand ka pramukh lok nritya kaun sa hai?',o:['Karma','Mach','Rai','Tertali'],a:2,n:'Rai = Bundelkhand ka major folk dance (Bediya community).'},
{c:"Ch.5 Rajya Prateek",q:'Karma lok nritya kahan prachlit hai?',o:['Malwa','Bundelkhand','Eastern MP (Balaghat, Mandla, Dindori)','Chambal'],a:2,n:'Karma = tribal folk dance of eastern MP.'},
{c:"Ch.5 Rajya Prateek",q:'Tertali dance kaunsi community karte hain?',o:['Bhil','Gond','Kamad tribe','Baiga'],a:2,n:'Tertali = Kamad tribe. Women dance with cymbals on legs.'},
{c:"Ch.5 Rajya Prateek",q:'Jawara dance kahan hota hai?',o:['Bundelkhand','Baghelkhand','Malwa harvest festival','Chambal'],a:2,n:'Jawara = Malwa harvest dance, women balance pots on head.'},
{c:"Ch.5 Rajya Prateek",q:'Saila dance kahan hota hai?',o:['Malwa','Bundelkhand & Baghelkhand','Eastern MP','Chambal'],a:1,n:'Saila = tribal dance of Bundelkhand & Baghelkhand, boys dance with sticks.'},
{c:"Ch.5 Rajya Prateek",q:'Mach Naatya kis cheez par aadharit hota hai?',o:['Aadivasi geet','Pauraanik (mythological) kathayen','News events','History of kings'],a:1,n:'Mach based on mythological stories and cultural themes.'},
{c:"Ch.5 Rajya Prateek",q:'Rajya khel ghoshna ke saath Malkhamb Academy kahan banayi gayi?',o:['Bhopal','Ujjain','Indore','Gwalior'],a:1,n:'Malkhamb Academy established in Ujjain.'},
{c:"Ch.5 Rajya Prateek",q:'Malkhamb ki utpatti kab hui?',o:['8th century','10th century','12th century','16th century'],a:2,n:'Malkhamb originated in the 12th century.'},
{c:"Ch.5 Rajya Prateek",q:'Rajya Pashu ghoshna kis din hui?',o:['1 November 1956','15 August 1981','1 November 1981','26 January 1982'],a:2,n:'State animal, bird, tree, flower declared on 1 November 1981 (25th foundation day).'},
{c:"Ch.6 Upnaam",q:"MP ko 'Heart of India' kyun kaha jaata hai?",o:['Sabse bada rajya','Sabse purana rajya','Geographically centre mein sthit','Sabse adhik nadi'],a:2,n:'MP is geographically at the centre, bordered by 5 states.'},
{c:"Ch.6 Upnaam",q:"'Madhya Pradesh' ka literal arth kya hai?",o:['Eastern State','Central Province','Middle Kingdom','Heart Province'],a:1,n:'Madhya = Central/Middle, Pradesh = Province/State.'},
{c:"Ch.6 Upnaam",q:"MP ko 'Laghu Bharat' kyun kaha jaata hai?",o:['Sabse bada rajya','46 tribal groups — highest in India','Sabse adhik nadiyan','Sabse purani sabhyata'],a:1,n:'46 tribal groups — highest in any Indian state.'},
{c:"Ch.6 Upnaam",q:'MP mein kitne tribal groups hain?',o:['36','40','46','52'],a:2,n:"46 tribal groups — highest in India. Hence 'Laghu Bharat.'"},
{c:"Ch.6 Upnaam",q:"MP ko 'Diamond State' kyun kaha jaata hai?",o:['Sabse adhik reserves','Ek hi diamond-producing state','Sabse adhik minerals','UNESCO site'],a:1,n:'MP is the ONLY diamond-producing state. Majhgawan mine, Panna.'},
{c:"Ch.6 Upnaam",q:'India mein sabse adhik heera reserves kahan hain?',o:['Madhya Pradesh','Andhra Pradesh','Jharkhand','Rajasthan'],a:1,n:'AP has highest diamond RESERVES; MP has only PRODUCTION. ★ Trap!'},
{c:"Ch.6 Upnaam",q:'MP mein diamond ka kaunsa mine hai?',o:['Golkonda mine','Majhgawan mine Panna','Panna open mine','Vijay mine Panna'],a:1,n:'Majhgawan mine in Panna, operated by NMDC.'},
{c:"Ch.6 Upnaam",q:"MP ko 'Soya State' kyun kaha jaata hai?",o:['Soyabean sabse purana crop','55–60% national soyabean production','Soyabean ka export','Soyabean research centre'],a:1,n:"MP = 55–60% of India's soyabean production."},
{c:"Ch.6 Upnaam",q:'2022 tiger census ke anusaar MP mein kitne tigers hain?',o:['625','726','785','850'],a:2,n:'785 tigers (2022) — highest in India. Overtook Karnataka.'},
{c:"Ch.6 Upnaam",q:'Tiger population mein MP ne Karnataka ko kab peeche chhoda?',o:['2018','2020','2022','2024'],a:2,n:'MP overtook Karnataka in 2022 tiger census.'},
{c:"Ch.6 Upnaam",q:"MP ko 'Nadiyon ka Maika' kyun kaha jaata hai?",o:['Sabse lambi nadi','MP se 9+ nadiyan nikalti hain','Sabse zyada pani','Sabse clean rivers'],a:1,n:'9+ major rivers originate in MP.'},
{c:"Ch.6 Upnaam",q:'MP mein leopard population India mein kaun se sthan par hai?',o:['2nd','3rd','1st','4th'],a:2,n:'MP has highest leopard population (WII survey).'},
{c:"Ch.6 Upnaam",q:"MP ko 'Tiger State' kyun kaha jaata hai?",o:['Sabse adhik National Parks','785 tigers (2022) — India mein highest','Sabse pahle Tiger Reserve','Tiger breeding programme'],a:1,n:'785 tigers — highest in India.'},
{c:"Ch.6 Upnaam",q:'MP mein kitne Tiger Reserves hain?',o:['5','6','7','8'],a:2,n:'7 Tiger Reserves: Bandhavgarh, Kanha, Pench, Satpura, Sanjay-Dubri, Panna, Nauradehi.'},
{c:"Ch.6 Upnaam",q:'Amarkantak se kaun si nadiyan nikalti hain?',o:['Narmada only','Narmada & Chambal','Narmada, Sone & Johila','Chambal & Betwa'],a:2,n:'3 rivers from Amarkantak: Narmada + Sone + Johila. ★'},
{c:"Ch.7 Capitals",q:'Bhopal ko kaun si rajdhani kaha jaata hai?',o:['Vyavsayik Rajdhani','Sanskritic Rajdhani','Rajdhani (Capital)','Dharmic Rajdhani'],a:2,n:'Bhopal = Rajdhani — Capital City of MP.'},
{c:"Ch.7 Capitals",q:'Bhopal ko aur kya kaha jaata hai?',o:['City of Palaces','Jheelon ka Shahar (City of Lakes)','City of Music','Diamond City'],a:1,n:'Bhopal = Jheelon ka Shahar (City of Lakes). Also Nawabi Shahar.'},
{c:"Ch.7 Capitals",q:'Bhopal gas tragedy mein kaun si gas leak hui?',o:['Chlorine','Ammonia','MIC (Methyl Isocyanate)','Hydrogen Cyanide'],a:2,n:'MIC (Methyl Isocyanate) from Union Carbide, 2–3 December 1984.'},
{c:"Ch.7 Capitals",q:'Bhopal gas tragedy kab hui?',o:['3–4 December 1984','2–3 December 1984','1–2 December 1984','4–5 December 1984'],a:1,n:"2–3 December 1984. World's worst industrial disaster."},
{c:"Ch.7 Capitals",q:'Bhopal gas tragedy kis company ki factory thi?',o:['Dow Chemicals','Union Carbide','DuPont','BASF'],a:1,n:'Union Carbide plant — Bhopal Gas Tragedy.'},
{c:"Ch.7 Capitals",q:'Bhoj Wetland (Bhopal) ko Ramsar site kab ghoshit kiya gaya?',o:['1987','1993','2002','2008'],a:2,n:'Bhoj Wetland declared Ramsar site in 2002.'},
{c:"Ch.7 Capitals",q:'Bhopal ka Upper Lake kiska naam hai?',o:['Bhoj Talab','Bada Talab','Nawabi Talab','Sher Shah Sagar'],a:1,n:'Upper Lake = Bada Talab / Bhoj Wetland. Built by Raja Bhoja.'},
{c:"Ch.7 Capitals",q:'Bhopal ki Begum sultaanat kab tak rahi?',o:['1757–1857','1819–1926','1857–1947','1800–1947'],a:1,n:'Begums ruled Bhopal from 1819 to 1926 — unique in Indian history.'},
{c:"Ch.7 Capitals",q:'Bhopal Airport ka naam kya hai?',o:['Devi Ahilyabai Holkar Airport','Raja Bhoj Airport','Rajmata Vijayaraje Scindia Airport','Bhimrao Ambedkar Airport'],a:1,n:'Raja Bhoj Airport — named after Paramara King Raja Bhoja.'},
{c:"Ch.7 Capitals",q:'Indore ko kaunsi rajdhani kaha jaata hai?',o:['Rajdhani','Vyavsayik Rajdhani','Dharmic Rajdhani','Paryatan Rajdhani'],a:1,n:'Indore = Vyavsayik Rajdhani (Commercial Capital).'},
{c:"Ch.7 Capitals",q:"Indore ko 'Mini Mumbai' kyun kaha jaata hai?",o:['Beach ke paas hai','Industrial, commercial, cosmopolitan character','Film studios','Stock exchange'],a:1,n:'Called Mini Mumbai for its industrial and commercial character.'},
{c:"Ch.7 Capitals",q:'Swachh Survekshan 2024 mein Indore ne kaunsa sthan prapt kiya?',o:['5th consecutive','6th consecutive','7th consecutive','8th consecutive'],a:3,n:'Indore won Cleanest City 8 consecutive times (2017–2024).'},
{c:"Ch.7 Capitals",q:'Sirpur Lake (Indore) kya hai?',o:['Tiger Reserve','Ramsar Wetland Site','Biosphere Reserve','Wildlife Sanctuary'],a:1,n:'Sirpur Lake = Ramsar Wetland site in Indore.'},
{c:"Ch.7 Capitals",q:'Chambal nadi ka udgam kahan hai?',o:['Betul','Amarkantak','Janapav Hill Mhow Indore','Kakra Bardi'],a:2,n:'Chambal originates from Janapav Hill, Mhow, Indore.'},
{c:"Ch.7 Capitals",q:'Shipra nadi ka udgam kahan hai?',o:['Amarkantak','Pachmarhi','Kakra Bardi Mountain Indore','Betul'],a:2,n:'Shipra originates from Kakra Bardi Mountain, Indore.'},
{c:"Ch.7 Capitals",q:'Pithampur (near Indore) ko kya kaha jaata hai?',o:['Silicon Valley of MP','Detroit of MP','Hollywood of MP','Manchester of MP'],a:1,n:"Pithampur = 'Detroit of MP' for automobile industry."},
{c:"Ch.7 Capitals",q:'Indore mein IIT kab sthapit hua?',o:['2004','2007','2009','2012'],a:2,n:'IIT Indore established 2009 at Simrol campus.'},
{c:"Ch.7 Capitals",q:'Indore mein IIM kab sthapit hua?',o:['1990','1993','1996','2000'],a:2,n:'IIM Indore established 1996.'},
{c:"Ch.7 Capitals",q:'Indore Airport ka naam kya hai?',o:['Raja Bhoj Airport','Devi Ahilyabai Holkar Airport','Rajmata VS Airport','Bhimrao Ambedkar Airport'],a:1,n:'Devi Ahilyabai Holkar Airport, Indore.'},
{c:"Ch.7 Capitals",q:"Indore ko 'Sports Capital' kyun kaha jaata hai?",o:['Kabaddi stadium','Holkar Cricket Stadium — major cricket venue','National Games hosted','Olympic training centre'],a:1,n:'Holkar Cricket Stadium — major IPL and international cricket venue.'},
{c:"Ch.7 Capitals",q:'Gwalior ko kaunsi rajdhani kaha jaata hai?',o:['Vyavsayik Rajdhani','Sanskritic Rajdhani','Dharmic Rajdhani','Urja Rajdhani'],a:1,n:'Gwalior = Sanskritic Rajdhani (Cultural Capital).'},
{c:"Ch.7 Capitals",q:'Gwalior ke baare mein Babur ne kya kaha?',o:["'Sone ka Panjara'","'Pearl among Fortresses in India'","'Crown of Central India'","'Gateway of Hindustan'"],a:1,n:"Babur called Gwalior Fort 'Pearl among the Fortresses in India.'"},
{c:"Ch.7 Capitals",q:'Tansen Samaroha kahan hota hai?',o:['Bhopal','Ujjain','Gwalior','Jabalpur'],a:2,n:'Tansen Samaroha — annually November–December at Gwalior.'},
{c:"Ch.7 Capitals",q:'Tansen kahan ke paas paida hue the?',o:['Gwalior fort mein','Behat near Gwalior','Ujjain mein','Bhopal mein'],a:1,n:'Tansen born at Behat village near Gwalior.'},
{c:"Ch.7 Capitals",q:'Gwalior Airport ka naam kya hai?',o:['Raja Bhoj Airport','Devi Ahilyabai Airport','Rajmata Vijayaraje Scindia Airport','Bhimrao Ambedkar Airport'],a:2,n:'Rajmata Vijayaraje Scindia Airport — largest runway in MP.'},
{c:"Ch.7 Capitals",q:'Gwalior kis dynasty ke shaasit tha?',o:['Holkar','Scindia (Maratha)','Bundela','Chandela'],a:1,n:'Gwalior ruled by Scindia (Maratha) dynasty.'},
{c:"Ch.7 Capitals",q:'Rajmata Vijayaraje Scindia ka kya mahatwa tha?',o:['Congress founding member','BJP founding figure','MP ke pahle CM','India ke pahle governor'],a:1,n:'Rajmata Vijayaraje Scindia was a BJP founding figure.'},
{c:"Ch.7 Capitals",q:'Jabalpur ko kaunsi rajdhani kaha jaata hai?',o:['Vyavsayik Rajdhani','Sanskritic Rajdhani','Dharmic Rajdhani','Urja Rajdhani'],a:1,n:'Jabalpur = Sanskritic Rajdhani (also Marble City, Legal Capital).'},
{c:"Ch.7 Capitals",q:'Bhedaghat kahan hai aur kiske liye prasiddh hai?',o:['Ujjain — Kumbh Mela','Jabalpur — Narmada marble gorge','Bhopal — Lakes','Panna — Diamonds'],a:1,n:'Bhedaghat near Jabalpur — Narmada river white marble gorge.'},
{c:"Ch.7 Capitals",q:'Dhuandhar Falls kahan hai?',o:['Pachmarhi','Bhedaghat Jabalpur','Amarkantak','Kanha NP'],a:1,n:'Dhuandhar Falls (Smoke Cascade) at Bhedaghat, Jabalpur.'},
{c:"Ch.7 Capitals",q:'Chausath Yogini Temple kahan hai?',o:['Khajuraho','Ujjain','Jabalpur (Bhedaghat)','Sanchi'],a:2,n:'Chausath Yogini Temple at Bhedaghat, Jabalpur (10th century, 81 Yogini sculptures).'},
{c:"Ch.7 Capitals",q:'MP ka uchcha nyayalay (High Court) kahan hai?',o:['Bhopal','Indore','Gwalior','Jabalpur'],a:3,n:'MP High Court main bench at Jabalpur.'},
{c:"Ch.7 Capitals",q:'Panna ko kaunsi rajdhani kaha jaata hai?',o:['Urja Rajdhani','Heera Rajdhani','Maneej Rajdhani','Cement Capital'],a:1,n:'Panna = Heera Rajdhani (Diamond Capital).'},
{c:"Ch.7 Capitals",q:'India mein diamond mining kahan hoti hai?',o:['Andhra Pradesh','Jharkhand','Panna MP','Gujarat'],a:2,n:'Panna (MP) = only active diamond mine in India.'},
{c:"Ch.7 Capitals",q:'Panna ki diamond mine ka naam kya hai?',o:['Golkonda mine','Majhgawan mine','Panna mine','Vijay mine'],a:1,n:'Majhgawan mine in Panna, operated by NMDC.'},
{c:"Ch.7 Capitals",q:'Panna Tiger Reserve ki kya visheshata hai?',o:['Sabse bada TR','Tigers reintroduce kiye gaye 2009 ke baad','Sabse purana TR','UNESCO listed'],a:1,n:'Panna TR: tigers went locally extinct by 2009, successfully reintroduced.'},
{c:"Ch.7 Capitals",q:'Ken-Betwa River Interlinking Project kahan se guzarta hai?',o:['Kanha NP','Satpura NP','Panna Tiger Reserve','Bandhavgarh TR'],a:2,n:'Ken-Betwa Project passes through Panna Tiger Reserve — controversial.'},
{c:"Ch.7 Capitals",q:'Panna kis sambhag mein hai?',o:['Rewa','Sagar','Jabalpur','Shahdol'],a:1,n:'Panna is in Sagar division.'},
{c:"Ch.7 Capitals",q:'Singrauli ko kaunsi rajdhani kaha jaata hai?',o:['Heera Rajdhani','Maneej Rajdhani','Urja Rajdhani + Coal Capital','Sangeet Rajdhani'],a:2,n:'Singrauli = Urja Rajdhani + Koyla Rajdhani + Coal Capital.'},
{c:"Ch.7 Capitals",q:'Singrauli kaunse number ka jila bana?',o:['48th','49th','50th','51st'],a:2,n:'50th district (24 May 2008) carved from Sidhi.'},
{c:"Ch.7 Capitals",q:'NTPC Vindhyachal kahan hai?',o:['Rewa','Satna','Singrauli','Shahdol'],a:2,n:"NTPC Vindhyachal (India's largest thermal plant, 4,760 MW) in Singrauli."},
{c:"Ch.7 Capitals",q:'NCL (Northern Coalfields Limited) kahan operate karta hai?',o:['Rewa','Shahdol','Singrauli','Panna'],a:2,n:'NCL operates in Singrauli coalfield.'},
{c:"Ch.7 Capitals",q:'Singrauli mein Asia ka sabse mota coal seam kahan hai?',o:['Sonbhadra','Singrauli coalfield','Dhanbad','Korba'],a:1,n:'Singrauli coalfield has thickest coal seam in Asia.'},
{c:"Ch.7 Capitals",q:'Ujjain ko kaunsi rajdhani kaha jaata hai?',o:['Vyavsayik Rajdhani','Dharmic Rajdhani','Sanskritic Rajdhani','Maneej Rajdhani'],a:1,n:'Ujjain = Dharmic Rajdhani (Religious Capital).'},
{c:"Ch.7 Capitals",q:'Mahakaleshwar Jyotirlinga ki kya visheshata hai?',o:['Sabse purana','Sabse bada','Ek maatra Dakshinamukhi','Sabse uncha'],a:2,n:'Mahakaleshwar = only Dakshinamukhi Jyotirlinga in India.'},
{c:"Ch.7 Capitals",q:'Simhastha Kumbh kahan aur kitne saal baad hota hai?',o:['Prayagraj — 6 years','Ujjain — 12 years','Nashik — 9 years','Haridwar — 15 years'],a:1,n:'Simhastha Kumbh = Ujjain, every 12 years on Shipra river.'},
{c:"Ch.7 Capitals",q:'Shipra nadi ke kinare kaun sa Kumbh hota hai?',o:['Pushkar Kumbh','Simhastha Kumbh Ujjain','Nashik Kumbh','Triveni Kumbh'],a:1,n:'Simhastha Kumbh Mela at Ujjain on Shipra (Kshipra) river.'},
{c:"Ch.7 Capitals",q:'Vikram Samvat ki shuruaat kab aur kisne ki?',o:['57 CE — Raja Bhoja','57 BCE — Vikramaditya','320 CE — Chandragupta','78 CE — Kanishka'],a:1,n:'Vikram Samvat = 57 BCE, started by Vikramaditya at Ujjain.'},
{c:"Ch.7 Capitals",q:'Kalidasa ka sambandh kahan se tha?',o:['Bhopal','Jabalpur','Ujjain (Vikramaditya ke Navratna)','Gwalior'],a:2,n:"Kalidasa was in Vikramaditya's Navratna court at Ujjain."},
{c:"Ch.7 Capitals",q:'Ujjain ancient India ka kaun sa reference point tha?',o:['Southern terminus','Prime Meridian','Northern Terminus','Eastern Gate'],a:1,n:'Ujjain was the prime meridian of ancient Indian astronomy.'},
{c:"Ch.7 Capitals",q:'Malkhamb Academy kahan hai?',o:['Bhopal','Indore','Gwalior','Ujjain'],a:3,n:'Malkhamb Academy is in Ujjain.'},
{c:"Ch.7 Capitals",q:'Pachmarhi ko kaunsi rajdhani kaha jaata hai?',o:['Vyavsayik Rajdhani','Dharmic Rajdhani','Paryatan + Greeshmakaleen Rajdhani','Urja Rajdhani'],a:2,n:'Pachmarhi = Paryatan Rajdhani + Greeshmakaleen Rajdhani + Satpura ki Rani.'},
{c:"Ch.7 Capitals",q:'Pachmarhi MP ka kaun si cheez hai?',o:['Sabse bada shahar','Ek maatra Hill Station','Sabse purana temple','Sabse bada dam'],a:1,n:'Pachmarhi = Only Hill Station of MP.'},
{c:"Ch.7 Capitals",q:'Pachmarhi kis district mein hai?',o:['Hoshangabad','Narmadapuram','Betul','Chhindwara'],a:1,n:'Pachmarhi is in Narmadapuram district (renamed from Hoshangabad, 28 Aug 2008).',u:'NOT Hoshangabad — renamed to Narmadapuram in 2008.'},
{c:"Ch.7 Capitals",q:'Pachmarhi ki discovery kisne ki?',o:['Captain Robert Napier','Captain James Forsyth','Lord Curzon','Lord Dalhousie'],a:1,n:'Captain James Forsyth (Bengal Lancers) discovered Pachmarhi in 1857.'},
{c:"Ch.7 Capitals",q:'MP ka sabse uncha shikhar Dhupgarh kahan hai?',o:['Vindhya Range','Kaimur Range','Satpura Range, Pachmarhi','Maikal Hills'],a:2,n:'Dhupgarh (1,352 m) in Satpura Range, Pachmarhi.'},
{c:"Ch.7 Capitals",q:'Pachmarhi Biosphere Reserve nationally kab ghoshit hua?',o:['1996','1999','2003','2009'],a:1,n:'Declared nationally 1999. UNESCO recognition May 2009.'},
{c:"Ch.7 Capitals",q:'MP ka sabse uncha waterfall kaun sa hai?',o:['Bee Falls','Dhuandhar Falls','Rajat Prapat (Silver Falls)','Kapil Dhara'],a:2,n:'Rajat Prapat (Silver Falls) at Pachmarhi = highest waterfall of MP (35 m).'},
{c:"Ch.7 Capitals",q:'Pachmarhi ka naam kaise pada?',o:['Pahad + Marhi','Panch (5) + Marhi (caves)','Pachar + Hi','Pachha + Mari'],a:1,n:'Panch (5) + Marhi (caves) = 5 caves where Pandavas lived.'},
{c:"Ch.7 Capitals",q:'Pachmarhi ka Biosphere Reserve kaunse National Park ko include karta hai?',o:['Kanha NP','Satpura NP','Bandhavgarh NP','Panna TR'],a:1,n:'Pachmarhi Biosphere includes Satpura National Park.'},
{c:"Ch.7 Capitals",q:'Balaghat ko kaunsi rajdhani kaha jaata hai?',o:['Urja Rajdhani','Heera Rajdhani','Maneej Rajdhani','Cement Capital'],a:2,n:'Balaghat = Maneej Rajdhani (Manganese Capital).'},
{c:"Ch.7 Capitals",q:'India ka sabse bada open-cast copper mine kahan hai?',o:['Rajasthan','Jharkhand','Malajkhand Balaghat MP','Karnataka'],a:2,n:"Malajkhand (Balaghat) = India's largest open-cast copper mine."},
{c:"Ch.7 Capitals",q:'Malajkhand copper mine ka sanchaalan kaun karta hai?',o:['NMDC','HCL (Hindustan Copper Limited)','SAIL','NALCO'],a:1,n:'Malajkhand operated by HCL (Hindustan Copper Limited).'},
{c:"Ch.7 Capitals",q:'Malajkhand copper mine kab inaugurated hua?',o:['1971','1975','1982','1991'],a:2,n:'Inaugurated by PM Indira Gandhi in 1982.'},
{c:"Ch.7 Capitals",q:'Balaghat kis National Park ke paas hai?',o:['Bandhavgarh NP','Kanha NP','Satpura NP','Panna TR'],a:1,n:'Balaghat is adjacent to Kanha National Park.'},
{c:"Ch.7 Capitals",q:'Maihar ko kaunsi rajdhani kaha jaata hai?',o:['Urja Rajdhani','Heera Rajdhani','Maneej Rajdhani','Sangeet Rajdhani'],a:3,n:'Maihar = Sangeet Rajdhani (Music Capital).'},
{c:"Ch.7 Capitals",q:'Maihar Gharana ke sansthapak kaun the?',o:['Ravi Shankar','Ustad Bismillah Khan','Ustad Alauddin Khan','Ali Akbar Khan'],a:2,n:'Ustad Alauddin Khan (1862–1972) founded Maihar Gharana.'},
{c:"Ch.7 Capitals",q:'Ustad Alauddin Khan ke prasiddh shishya kaun the?',o:['Bismillah Khan & Zakir Hussain','Ravi Shankar & Ali Akbar Khan','Hariprasad Chaurasia & Shiv Kumar','Amjad Ali & Zakir'],a:1,n:'Guru of Ravi Shankar & Ali Akbar Khan.'},
{c:"Ch.7 Capitals",q:'Sharda Mata Temple kahan hai?',o:['Amarkantak','Maihar (Trikut Hill)','Omkareshwar','Chitrakoot'],a:1,n:'Sharda Mata Temple at Maihar on Trikut Hill — 1,063 steps.'},
{c:"Ch.7 Capitals",q:'Maihar 2023 mein kaun se jile se bana?',o:['Rewa','Chhindwara','Satna','Sidhi'],a:2,n:'Maihar carved from Satna district in 2023.'},
{c:"Ch.7 Capitals",q:'Rewa ko kya kaha jaata hai?',o:['Heera Rajdhani','Safed Sher ki Dharti','Urja Rajdhani','Maneej Rajdhani'],a:1,n:'Rewa = Safed Sher ki Dharti (Land of White Tigers).'},
{c:"Ch.7 Capitals",q:'Pahla white tiger kab aur kahan mila tha?',o:['Bandhavgarh 1948','Kanha 1955','Rewa 1951','Panna 1960'],a:2,n:'First white tiger found in Rewa in 1951 by Maharaja Martand Singh.'},
{c:"Ch.7 Capitals",q:'Rewa Solar Park ki capacity kitni hai?',o:['500 MW','650 MW','750 MW','1,000 MW'],a:2,n:'750 MW Solar Park, Gurh Tehsil, Rewa.'},
{c:"Ch.7 Capitals",q:'Rewa Solar Park se kaun sa project bijli leta hai?',o:['Delhi Airport','Delhi Metro','Delhi Jal Board','Delhi Government'],a:1,n:'Rewa Solar Park powers Delhi Metro (since 2020).'},
{c:"Ch.7 Capitals",q:'Khajuraho ko UNESCO World Heritage kab mila?',o:['1982','1986','1989','2003'],a:1,n:'Khajuraho UNESCO World Heritage = 1986.'},
{c:"Ch.7 Capitals",q:'Khajuraho kis dynasty ne banwaya tha?',o:['Paramara','Holkar','Chandela','Bundela'],a:2,n:'Khajuraho built by Chandela dynasty.'},
{c:"Ch.7 Capitals",q:'Khajuraho kis district mein hai?',o:['Panna','Sagar','Chhatarpur','Damoh'],a:2,n:'Khajuraho is in Chhatarpur district, Sagar division.'},
{c:"Ch.7 Capitals",q:'Sanchi Stupa ko UNESCO World Heritage kab mila?',o:['1986','1989','1993','2003'],a:1,n:'Sanchi Buddhist Monuments UNESCO = 1989.'},
{c:"Ch.7 Capitals",q:'Sanchi kis district mein hai?',o:['Bhopal','Vidisha','Raisen','Sehore'],a:2,n:'Sanchi is in Raisen district, Bhopal division.'},
{c:"Ch.7 Capitals",q:'Bhimbetka rock shelters ko UNESCO kab mila?',o:['1999','2001','2003','2005'],a:2,n:'Bhimbetka UNESCO = 2003. 10,000+ year old rock paintings.'},
{c:"Ch.7 Capitals",q:'Bhimbetka kis district mein hai?',o:['Bhopal','Vidisha','Raisen','Sehore'],a:2,n:'Bhimbetka is in Raisen district, Bhopal division.'},
{c:"Ch.7 Capitals",q:'India mein Currency Note Press kitni jagah hain?',o:['2','3','4','5'],a:2,n:'4 Currency Note Printing Presses in India (RBI). MP = Dewas.'},
{c:"Ch.7 Capitals",q:'Dewas mein kaun sa pramukh karyalay hai?',o:['IIT campus','Currency Note Press','NIT campus','NMDC office'],a:1,n:'Currency Note Press at Dewas — 1 of only 4 in India.'},
{c:"Ch.7 Capitals",q:'Satna ko kya kaha jaata hai?',o:['Urja Rajdhani','Heera Rajdhani','Cement Capital of MP','Sangeet Rajdhani'],a:2,n:'Satna = Cement Capital of MP (largest cement cluster).'},
{c:"Ch.7 Capitals",q:'Mandsaur kaunsi anek visheshata ke liye jana jaata hai?',o:['Tea & Coffee','Opium city + Only slate producer in India','Diamond & Copper','Jute & Cotton'],a:1,n:'Mandsaur = Opium City + Only slate pencil producer in India.'},
{c:"Ch.7 Capitals",q:'Khandwa kis musician ke janmasthan ke liye prasiddh hai?',o:['Ravi Shankar','Kishore Kumar','Lata Mangeshkar','Tansen'],a:1,n:'Khandwa = birthplace of Kishore Kumar.'},
{c:"Ch.8 Prashasan",q:'MP mein 2026 mein kitne jile hain?',o:['51','52','53','55'],a:3,n:'55 districts (3 new in 2023).',u:'Updated: 52 → 55.'},
{c:"Ch.8 Prashasan",q:'2023 mein kaun se 3 naye jile bane?',o:['Agar Malwa, Niwari, Mauganj','Mauganj, Maihar, Pandhurna','Maihar, Niwari, Pandhurna','Singrauli, Agar Malwa, Maihar'],a:1,n:'Mauganj (from Rewa), Maihar (from Satna), Pandhurna (from Chhindwara).'},
{c:"Ch.8 Prashasan",q:'51va jila kaunsa bana?',o:['Niwari','Singrauli','Agar Malwa','Mauganj'],a:2,n:'Agar Malwa = 51st district (2013, from Shajapur).'},
{c:"Ch.8 Prashasan",q:'52va jila kaunsa bana?',o:['Agar Malwa','Niwari','Mauganj','Pandhurna'],a:1,n:'Niwari = 52nd district (24 May 2018, from Tikamgarh).'},
{c:"Ch.8 Prashasan",q:'Niwari jila kahan se bana tha?',o:['Shajapur','Satna','Tikamgarh','Sagar'],a:2,n:'Niwari carved from Tikamgarh on 24 May 2018.'},
{c:"Ch.8 Prashasan",q:'Maihar jila kahan se bana tha?',o:['Rewa','Satna','Chhindwara','Sidhi'],a:1,n:'Maihar carved from Satna in 2023.'},
{c:"Ch.8 Prashasan",q:'Mauganj jila kahan se bana tha?',o:['Satna','Chhindwara','Rewa','Jabalpur'],a:2,n:'Mauganj carved from Rewa in 2023.'},
{c:"Ch.8 Prashasan",q:'Pandhurna jila kahan se bana tha?',o:['Chhindwara','Betul','Mandla','Narsinghpur'],a:0,n:'Pandhurna carved from Chhindwara in 2023.'},
{c:"Ch.8 Prashasan",q:'MP mein kitne sambhag (divisions) hain?',o:['8','9','10','12'],a:2,n:'10 administrative divisions in MP.'},
{c:"Ch.8 Prashasan",q:'MP mein kitni tehsilen hain (2026)?',o:['313','371','428','450'],a:2,n:'428 tehsils.',u:'Updated: 371 → 428.'},
{c:"Ch.8 Prashasan",q:'MP mein kitne Vikas Khanda hain?',o:['290','313','330','350'],a:1,n:'313 Janpad Panchayats / Vikas Khanda.'},
{c:"Ch.8 Prashasan",q:'MP mein kitne Aadivasi Vikas Khanda hain?',o:['79','89','99','109'],a:1,n:'89 Aadivasi Vikas Khanda.'},
{c:"Ch.8 Prashasan",q:'MP mein gram panchayaton ki sankhya (2026)?',o:['22,816','~23,043','25,000','21,000'],a:1,n:'~23,043 gram panchayats.',u:'Updated: 22,816 → ~23,043.'},
{c:"Ch.8 Prashasan",q:'MP mein Nagar Nigam ki sankhya?',o:['14','16','18','20'],a:2,n:'18 Nagar Nigam.',u:'Updated: 16 → 18.'},
{c:"Ch.8 Prashasan",q:'MP mein Nagar Palika ki sankhya?',o:['89','98','100','110'],a:2,n:'100 Nagar Palikas.',u:'Updated: 98 → 100.'},
{c:"Ch.8 Prashasan",q:'MP mein Nagar Panchayat ki sankhya?',o:['264','272','280','300'],a:0,n:'264 Nagar Panchayats.',u:'Updated: 272 → 264.'},
{c:"Ch.8 Prashasan",q:'MP mein kul ULB (Urban Local Bodies) kitni hain?',o:['380','382','390','400'],a:1,n:'382 ULBs = 18+100+264.',u:'Updated: 476 → 382.'},
{c:"Ch.8 Prashasan",q:'Ksheatrafal mein MP ka sabse bada jila?',o:['Mandla','Rewa','Chhindwara','Sagar'],a:2,n:'Chhindwara = largest district (11,815 sq km).'},
{c:"Ch.8 Prashasan",q:'Ksheatrafal mein MP ka sabse chhota jila?',o:['Datia','Niwari','Bhopal','Sheopur'],a:1,n:'Niwari = smallest district (1,170 sq km).'},
{c:"Ch.8 Prashasan",q:'Bhopal sambhag mein kitne jile hain?',o:['4','5','6','7'],a:1,n:'Bhopal sambhag = 5 districts: Bhopal, Vidisha, Raisen, Rajgarh, Sehore.'},
{c:"Ch.8 Prashasan",q:'Chambal sambhag mein kitne jile hain?',o:['2','3','4','5'],a:1,n:'Chambal sambhag = 3 districts: Morena, Bhind, Sheopur.'},
{c:"Ch.8 Prashasan",q:'Gwalior sambhag mein kitne jile hain?',o:['4','5','6','7'],a:1,n:'Gwalior sambhag = 5: Gwalior, Guna, Shivpuri, Datia, Ashoknagar.'},
{c:"Ch.8 Prashasan",q:'Indore sambhag mein kitne jile hain?',o:['6','7','8','9'],a:2,n:'Indore sambhag = 8 districts.'},
{c:"Ch.8 Prashasan",q:'Jabalpur sambhag mein kitne jile hain (2026)?',o:['7','8','9','10'],a:2,n:'Jabalpur sambhag = 9 (including Pandhurna added 2023).'},
{c:"Ch.8 Prashasan",q:'Narmadapuram sambhag mein kitne jile hain?',o:['2','3','4','5'],a:1,n:'Narmadapuram sambhag = 3: Narmadapuram, Betul, Harda.'},
{c:"Ch.8 Prashasan",q:'Rewa sambhag mein 2026 mein kitne jile hain?',o:['4','5','6','7'],a:1,n:'Rewa sambhag = 5 (including Mauganj added 2023).'},
{c:"Ch.8 Prashasan",q:'Sagar sambhag mein kitne jile hain?',o:['5','6','7','8'],a:1,n:'Sagar sambhag = 6: Sagar, Panna, Damoh, Chhatarpur, Tikamgarh, Niwari.'},
{c:"Ch.8 Prashasan",q:'Shahdol sambhag mein kitne jile hain?',o:['2','3','4','5'],a:1,n:'Shahdol sambhag = 3: Shahdol, Anuppur, Umaria.'},
{c:"Ch.8 Prashasan",q:'Ujjain sambhag mein kitne jile hain?',o:['5','6','7','8'],a:2,n:'Ujjain sambhag = 7: Ujjain, Shajapur, Dewas, Agar-Malwa, Ratlam, Mandsaur, Neemuch.'},
{c:"Ch.8 Prashasan",q:'Narmadapuram Division ka purana naam kya tha?',o:['Sehore Division','Hoshangabad Division','Betul Division','Narmada Division'],a:1,n:'Renamed from Hoshangabad to Narmadapuram Division on 28 August 2008.'},
{c:"Ch.8 Prashasan",q:'MP ki sthaapana ke waqt (1 Nov 1956) kitne jile the?',o:['40','43','45','50'],a:1,n:'43 districts at formation.'},
{c:"Ch.8 Prashasan",q:'26 January 1972 ko MP mein kitne naye jile bane?',o:['1','2','3','4'],a:1,n:'2 new districts: Bhopal & Rajnandgaon.'},
{c:"Ch.8 Prashasan",q:'Singrauli kab MP ka 50va jila bana?',o:['1 November 2000','24 May 2008','24 May 2018','2023'],a:1,n:'Singrauli = 50th district on 24 May 2008.'},
{c:"Ch.8 Prashasan",q:'Agar Malwa kab 51va jila bana?',o:['2010','2011','2013','2015'],a:2,n:'Agar Malwa = 51st district in 2013 (from Shajapur).'},
{c:"Ch.8 Prashasan",q:'Niwari kab 52va jila bana?',o:['2015','2016','2017','2018'],a:3,n:'Niwari = 52nd district on 24 May 2018.'},
{c:"Ch.8 Prashasan",q:'Sabse chhote sambhag (kam jile) mein kaun se hain?',o:['Chambal, Narmadapuram, Shahdol — 3 districts each','Bhopal, Gwalior — 5 districts','Jabalpur, Indore — 8 districts','Ujjain, Rewa — 7 districts'],a:0,n:'Chambal, Narmadapuram, and Shahdol each have only 3 districts.'},
{c:"Ch.8 Prashasan",q:'Sabse bade sambhag (adhik jile) mein kaun sa hai?',o:['Bhopal (5)','Gwalior (5)','Jabalpur (9)','Indore (8)'],a:2,n:'Jabalpur sambhag has 9 districts — most in any division.'},
{c:"Ch.8 Prashasan",q:'Chachaura & Nagda districts ke baare mein kya sach hai?',o:['Pehle se bane hain','18 March 2020 ko approve par abhi officially nahin bane','Cancelled permanently','2023 mein bane'],a:1,n:'Chachaura & Nagda approved 18 March 2020, not yet officially formed as of March 2026.'},
{c:"Ch.8 Prashasan",q:'MP mein Jila Panchayat ki sankhya kitni hai?',o:['50','52','55','60'],a:2,n:'55 Jila Panchayats (same as number of districts).'},
{c:"Ch.8 Prashasan",q:'Indore sambhag mein kaun sa naya jila nahin tha (2023)?',o:['Alirajpur','Barwani','Pandhurna','Burhanpur'],a:2,n:'Pandhurna added to Jabalpur sambhag, not Indore.'},
{c:"Ch.9 Rajneetik",q:'MP mein Lok Sabha ki kitni seeten hain?',o:['26','28','29','30'],a:2,n:'29 Lok Sabha seats in MP.'},
{c:"Ch.9 Rajneetik",q:'MP mein Rajya Sabha ki kitni seeten hain?',o:['9','10','11','12'],a:2,n:'11 Rajya Sabha seats.'},
{c:"Ch.9 Rajneetik",q:'MP mein Vidhan Sabha ki kitni seeten hain?',o:['200','220','230','240'],a:2,n:'230 VS seats (reduced from 320 after CG separation).'},
{c:"Ch.9 Rajneetik",q:'MP VS mein SC ke liye kitni seeten arakshit hain?',o:['25','30','35','40'],a:2,n:'35 SC reserved seats.'},
{c:"Ch.9 Rajneetik",q:'MP VS mein ST ke liye kitni seeten arakshit hain?',o:['37','42','47','52'],a:2,n:'47 ST reserved seats.'},
{c:"Ch.9 Rajneetik",q:'MP ke vartaman CM (March 2026) kaun hain?',o:['Shivraj Singh Chouhan','Kamal Nath','Mohan Yadav','Narendra Singh Tomar'],a:2,n:'Mohan Yadav (BJP) — sworn in 13 December 2023.',u:'Shivraj → Mohan Yadav.'},
{c:"Ch.9 Rajneetik",q:'Mohan Yadav kab MP ke CM bane?',o:['1 November 2023','13 December 2023','26 January 2024','15 March 2024'],a:1,n:'Sworn in 13 December 2023.'},
{c:"Ch.9 Rajneetik",q:'MP ke vartaman Governor (2026) kaun hain?',o:['Lalji Tandon','Anandiben Patel','Mangu Bhai Patel','Ram Naresh Yadav'],a:2,n:'Mangu Bhai Patel — current Governor.'},
{c:"Ch.9 Rajneetik",q:'MP mein Lok Sabha 2024 mein BJP ne kitni seeten jeeti?',o:['25/29','27/29','28/29','29/29'],a:3,n:'BJP won all 29/29 seats.'},
{c:"Ch.9 Rajneetik",q:'Vidhan Sabha 2023 mein BJP ko kitni seeten mili?',o:['152','163','175','185'],a:1,n:'BJP: 163, INC: 66, Others: 1 (total 230).'},
{c:"Ch.9 Rajneetik",q:'Vidhan Sabha 2023 mein INC ko kitni seeten mili?',o:['50','60','66','75'],a:2,n:'INC = 66 seats in 2023 VS.'},
{c:"Ch.9 Rajneetik",q:'Shivraj Singh Chouhan ne MP mein kitni baar CM ka pad sambhala?',o:['2 terms','3 terms','4 terms','5 terms'],a:2,n:'Shivraj = 4 terms CM (2005–2023) — longest-serving.'},
{c:"Ch.9 Rajneetik",q:'MP VS ki seeten CG alag hone ke baad kitni reh gayi?',o:['250','230','220','200'],a:1,n:'After CG separation (Nov 2000): 320 → 230 seats.'},
{c:"Ch.9 Rajneetik",q:'MP ke Deputy CMs (2026) kaun hain?',o:['Kailash Vijayvargiya & Prahlad Patel','Rajendra Shukla & Jagdish Devda','Narendra Singh Tomar & VD Sharma','Shivraj & Uma Bharti'],a:1,n:'Rajendra Shukla & Jagdish Devda.'},
{c:"Ch.9 Rajneetik",q:'MP ka pratham CM kaun tha?',o:['Kailash Nath Katju','B.P. Sitaramaiya','D.P. Mishra','Ravi Shankar Shukla'],a:3,n:'Ravi Shankar Shukla — 1st CM.'},
{c:"Ch.9 Rajneetik",q:'MP ka pratham Rajyapal kaun tha?',o:['Fazal Ali','Ravi Shankar Shukla','B.P. Sitaramaiya','Hridaynath Kunzru'],a:2,n:'B.P. Sitaramaiya — 1st Governor.'},
{c:"Ch.9 Rajneetik",q:'Chhattisgarh alag hone ke baad MP VS mein kitni seeten kum hui?',o:['50','70','90','100 (320 se 230)'],a:3,n:'320 – 230 = 90 seats reduced.'},
{c:"Ch.9 Rajneetik",q:'Lok Sabha 2024 mein INC ne MP mein kitni seeten jeeti?',o:['0','2','5','8'],a:0,n:'INC won 0 seats in MP 2024 Lok Sabha (BJP swept all 29).'},
{c:"Ch.9 Rajneetik",q:'MP mein Parliament ki kul kitni seeten hain (LS+RS)?',o:['38','40','42','44'],a:1,n:'29 LS + 11 RS = 40 total Parliament seats.'},
{c:"Ch.9 Rajneetik",q:'Kab se MP 5va sabse zyada aabaadi wala rajya bana?',o:['2011','2014','2016','2018'],a:1,n:'Since 2014 (after 2011 Census analysis), MP = 5th most populous.'},
{c:"Ch.10 Divas & Varsh",q:'MP Diwas kab manaya jaata hai?',o:['15 August','26 January','1 November','2 October'],a:2,n:'MP Diwas = 1 November (every year).'},
{c:"Ch.10 Divas & Varsh",q:'Beti Bachao Diwas kab hai?',o:['8 March','5 October','25 December','11 May'],a:1,n:'Beti Bachao Diwas = 5 October.'},
{c:"Ch.10 Divas & Varsh",q:'Sushasan Diwas kab manaya jaata hai?',o:['2 October','25 September','25 December','26 January'],a:2,n:'Sushasan Diwas = 25 December.'},
{c:"Ch.10 Divas & Varsh",q:'Lokasewa Diwas kab hai?',o:['11 May','18 June','25 September','2 November'],a:2,n:'Lokasewa Diwas = 25 September.'},
{c:"Ch.10 Divas & Varsh",q:'Panchayati Raj Diwas kab manaya jaata hai?',o:['2 October','25 January','26 January','25 September'],a:1,n:'Panchayati Raj Diwas = 25 January.'},
{c:"Ch.10 Divas & Varsh",q:'Janasankhya Niyantran Diwas kab hai?',o:['11 May','18 June','5 October','2 November'],a:0,n:'Janasankhya Niyantran Diwas = 11 May.'},
{c:"Ch.10 Divas & Varsh",q:'Mahila Sashaktikaran Diwas kab hai?',o:['8 March','11 May','18 June','25 September'],a:2,n:'Mahila Sashaktikaran Diwas = 18 June.'},
{c:"Ch.10 Divas & Varsh",q:'Nagariya Nikaay Diwas kab hai?',o:['1 November','2 November','3 November','5 November'],a:1,n:'Nagariya Nikaay Diwas = 2 November.'},
{c:"Ch.10 Divas & Varsh",q:'Mahua Diwas kab ghoshit hua?',o:['11 July 2009','11 July 2010','11 July 2011','11 July 2012'],a:2,n:'Mahua Diwas = 11 July 2011.'},
{c:"Ch.10 Divas & Varsh",q:'Kartavya Parv kab se kab tak hota hai?',o:['1–2 October','2–8 October','25 Sep – 2 Oct','26 Sep – 2 Oct'],a:2,n:'Kartavya Parv = 25 September to 2 October.'},
{c:"Ch.10 Divas & Varsh",q:'Vikas Diwas kab hai?',o:['6 March 2013','6 April 2013','6 May 2013','6 June 2013'],a:1,n:'Vikas Diwas = 6 April 2013.'},
{c:"Ch.10 Divas & Varsh",q:'Mahua Varsh kaunsa saal tha?',o:['2010','2011','2012','2013'],a:1,n:'Mahua Varsh = 2011.'},
{c:"Ch.10 Divas & Varsh",q:'Tikaakaran Varsh kaunsa saal tha?',o:['2011','2012','2013','2014'],a:1,n:'Tikaakaran Varsh = 2012.'},
{c:"Ch.10 Divas & Varsh",q:'Soochana Praudyogiki Varsh kaunsa saal tha?',o:['2012','2013','2014','2015'],a:1,n:'Soochana Praudyogiki (IT) Varsh = 2013.'},
{c:"Ch.10 Divas & Varsh",q:'Paryatan Varsh kaunsa saal tha?',o:['2013','2014','2015','2016'],a:2,n:'Paryatan Varsh = 2015.'},
{c:"Ch.10 Divas & Varsh",q:'Gareeb Kalyan Varsh kaunsa saal tha?',o:['2014','2015','2016','2017'],a:2,n:'Gareeb Kalyan Varsh = 2016.'},
{c:"Ch.10 Divas & Varsh",q:'MP ki sthaapana kab hui thi (for MP Diwas)?',o:['1 November 1952','1 November 1956','1 November 1960','1 November 1965'],a:1,n:'MP formed on 1 November 1956.'},
{c:"Ch.10 Divas & Varsh",q:'Kaunsa Diwas 25 December ko manaya jaata hai?',o:['Panchayati Raj Diwas','Sushasan Diwas','Lokasewa Diwas','Beti Bachao Diwas'],a:1,n:'Sushasan Diwas = 25 December.'},
{c:"Ch.11 Gathan",q:'1947 mein Central Provinces ka Category A mein kaunsa rajya bana?',o:['Vindhya Pradesh','Madhya Bharat','Madhya Pradesh','Bhopal State'],a:2,n:'Central Provinces + Baghelkhand + Chhattisgarh → MP (Category A). Capital: Nagpur.'},
{c:"Ch.11 Gathan",q:'Madhya Bharat (Category B) ki rajdhaniyaan kaun si theen?',o:['Bhopal & Rewa','Nagpur & Gwalior','Indore & Gwalior','Jabalpur & Rewa'],a:2,n:'Madhya Bharat had dual capitals: Indore & Gwalior.'},
{c:"Ch.11 Gathan",q:'Vindhya Pradesh (Category C) ki rajdhani kaun si thi?',o:['Bhopal','Rewa','Indore','Gwalior'],a:1,n:'Vindhya Pradesh = capital at Rewa.'},
{c:"Ch.11 Gathan",q:'State Reorganisation Commission ke adhyaksh kaun the?',o:['K.M. Panikkar','Hridaynath Kunzru','Fazal Ali','B.P. Sitaramaiya'],a:2,n:'Fazal Ali = Chairman, SRC.'},
{c:"Ch.11 Gathan",q:'SRC ke teen members kaun se the?',o:['Fazal Ali, Hridaynath Kunzru, K.M. Panikkar','B.P. Sitaramaiya, Fazal Ali, Kunzru','Panikkar, Nehru, Sitaramaiya','Only Fazal Ali'],a:0,n:'Fazal Ali (Chair), Hridaynath Kunzru, K.M. Panikkar.'},
{c:"Ch.11 Gathan",q:'1 Nov 1956 ko MP se kaun se jile Bombay State mein gaye?',o:['Nagpur, Akola, Amravati aadi 8 jile','Pune, Nashik, Aurangabad','Sholapur, Kolhapur','Nanded, Osmanabad'],a:0,n:'8 districts: Buldhana, Akola, Amravati, Yavatmal, Wardha, Nagpur, Bhandara, Chanda → Bombay.'},
{c:"Ch.11 Gathan",q:'1 Nov 1956 ko Rajasthan ke kaunse jile ki tehsil MP mein aayi?',o:['Kota — Baran tehsil','Kota — Sironje tehsil','Bundi tehsil','Jhalawar tehsil'],a:1,n:"Kota's Sironje Tehsil → Vidisha district, MP."},
{c:"Ch.11 Gathan",q:'Mandsaur ka Bhanpura area kahan se MP mein aaya?',o:['Bombay State','Part-C state','Rajasthan','UP'],a:1,n:'Bhanpura area of Mandsaur (except Sunel Tapla) from Part-C state.'},
{c:"Ch.11 Gathan",q:'1 Nov 1956 ko naye MP mein kitne jile the?',o:['40','43','45','50'],a:1,n:'43 districts at formation.'},
{c:"Ch.11 Gathan",q:'26 January 1972 ko kaun se naye jile bane?',o:['1 — Bhopal','2 — Bhopal & Rajnandgaon','3 — Bhopal, Rajnandgaon & Singrauli','2 — Gwalior & Jabalpur'],a:1,n:'Bhopal & Rajnandgaon. Total = 45.'},
{c:"Ch.11 Gathan",q:'Chhattisgarh kab alag hua?',o:['15 August 1999','1 November 2000','2 June 2000','1 November 2001'],a:1,n:'Chhattisgarh = 26th state on 1 November 2000.'},
{c:"Ch.11 Gathan",q:'Chhattisgarh kaun sa rajya bana?',o:['25th','26th','27th','28th'],a:1,n:'Chhattisgarh = 26th state of India.'},
{c:"Ch.11 Gathan",q:'CG alag hone ke baad MP VS ki seeten kitni reh gayi?',o:['250','230','220','200'],a:1,n:'320 → 230 after CG separation.'},
{c:"Ch.11 Gathan",q:'Singrauli kab MP ka 50va jila bana?',o:['1 November 2000','24 May 2008','24 May 2018','2023'],a:1,n:'Singrauli = 50th on 24 May 2008.'},
{c:"Ch.11 Gathan",q:'Agar Malwa kab MP ka 51va jila bana?',o:['2010','2011','2013','2015'],a:2,n:'Agar Malwa = 51st in 2013.'},
{c:"Ch.11 Gathan",q:'Niwari kab 52va jila bana?',o:['2015','2016','2017','24 May 2018'],a:3,n:'Niwari = 52nd on 24 May 2018.'},
{c:"Ch.11 Gathan",q:'2023 mein kaun se teen naye jile bane?',o:['Agar Malwa, Niwari, Mauganj','Mauganj, Maihar, Pandhurna','Maihar, Niwari, Pandhurna','Singrauli, Agar Malwa, Maihar'],a:1,n:'Mauganj, Maihar, Pandhurna.'},
{c:"Ch.11 Gathan",q:'Chachaura & Nagda districts kab approve hue?',o:['2018','2019','18 March 2020','2022'],a:2,n:'Approved 18 March 2020 but not yet officially formed.'},
{c:"Ch.11 Gathan",q:'8 September 1992 ko MP mein kitne naye jile propose kiye gaye?',o:['8','12','16','20'],a:2,n:'16 new districts proposed on 8 Sep 1992.'},
{c:"Ch.11 Gathan",q:'Naye MP ki pahli rajdhani kya thi?',o:['Nagpur','Indore','Bhopal','Gwalior'],a:2,n:'Bhopal became capital of new MP from 1 November 1956.'},
{c:"Ch.12 Geography",q:'MP ka sabse uncha shikhar (peak) kaun sa hai?',o:['Pachmarhi Peak','Dhupgarh (1,352 m)','Amarkantak','Maikal Top'],a:1,n:'Dhupgarh = 1,352 m, Satpura Range, Pachmarhi.',u:'1,352 m — not 1,350 m.'},
{c:"Ch.12 Geography",q:'Dhupgarh kis parwat shrenee mein hai?',o:['Vindhya Range','Kaimur Range','Satpura Range','Maikal Hills'],a:2,n:'Dhupgarh is in Satpura Range.'},
{c:"Ch.12 Geography",q:'Dhupgarh kahan ka sabse uncha bindu hai?',o:['Vindhya Range','Satpura Range','Maikal Hills','Kaimur Range'],a:1,n:'Dhupgarh = highest point of Satpura Range.'},
{c:"Ch.12 Geography",q:'MP mein kitne Tiger Reserves hain?',o:['5','6','7','8'],a:2,n:'7 TR: Bandhavgarh, Kanha, Pench, Satpura, Sanjay-Dubri, Panna, Nauradehi.'},
{c:"Ch.12 Geography",q:'MP mein kitne National Parks hain?',o:['9','10','11','12'],a:2,n:'11 National Parks in MP.'},
{c:"Ch.12 Geography",q:'MP mein kitne Biosphere Reserves hain?',o:['2','3','4','5'],a:1,n:'3: Pachmarhi, Amarkantak, Panna.'},
{c:"Ch.12 Geography",q:'Pachmarhi Biosphere nationally kab ghoshit hua?',o:['1996','1999','2003','2009'],a:1,n:'1999 nationally. UNESCO May 2009.'},
{c:"Ch.12 Geography",q:'MP mein Ramsar sites kitni hain?',o:['1','2','3','4'],a:1,n:'2 Ramsar sites: Bhoj Wetland (Bhopal) & Sirpur Lake (Indore).'},
{c:"Ch.12 Geography",q:'Bhoj Wetland kahan hai?',o:['Indore','Gwalior','Bhopal','Ujjain'],a:2,n:'Bhoj Wetland (Upper Lake) = Bhopal. Ramsar site 2002.'},
{c:"Ch.12 Geography",q:'Sirpur Lake kahan hai?',o:['Bhopal','Gwalior','Indore','Ujjain'],a:2,n:'Sirpur Lake = Indore. Ramsar site.'},
{c:"Ch.12 Geography",q:'MP mein forest cover approximately kitna hai?',o:['20.7%','25.7%','30.7%','35.7%'],a:2,n:'~30.7% forest cover. 1st rank in India (FSI 2023).'},
{c:"Ch.12 Geography",q:'Forest area mein MP ka India mein rank kaun sa hai?',o:['2nd','3rd','1st','4th'],a:2,n:'1st rank (FSI 2023).',u:'Updated: 3rd → 1st.'},
{c:"Ch.12 Geography",q:'Kanha National Park kis jile mein hai?',o:['Balaghat','Mandla','Seoni','Dindori'],a:1,n:'Kanha Kisli NP is in Mandla district.'},
{c:"Ch.12 Geography",q:'Bandhavgarh National Park kis jile mein hai?',o:['Shahdol','Satna','Umaria','Rewa'],a:2,n:'Bandhavgarh is in Umaria district.'},
{c:"Ch.12 Geography",q:'Satpura National Park kis jile mein hai?',o:['Narmadapuram','Betul','Harda','Chhindwara'],a:0,n:'Satpura NP is in Narmadapuram (Hoshangabad) district.'},
{c:"Ch.12 Geography",q:'Van Vihar National Park kahan hai?',o:['Indore','Gwalior','Bhopal','Jabalpur'],a:2,n:'Van Vihar NP is in Bhopal.'},
{c:"Ch.12 Geography",q:'Kuno National Park kahan hai?',o:['Sheopur','Morena','Bhind','Gwalior'],a:0,n:'Kuno NP (Cheetah project) is in Sheopur district.'},
{c:"Ch.12 Geography",q:'MP mein heeron ka kitna pratishat national production hai?',o:['70%','80%','90%','100%'],a:2,n:"~90% of India's diamond production from Panna."},
{c:"Ch.12 Geography",q:'Narmada nadi ka udgam kahan hai?',o:['Pachmarhi','Pench','Amarkantak (Anuppur)','Betul'],a:2,n:'Narmada originates from Amarkantak, Anuppur.'},
{c:"Ch.12 Geography",q:'Narmada nadi ki kul lambai kitni hai?',o:['1,077 km','1,200 km','1,312 km','1,500 km'],a:2,n:'Total: 1,312 km. In MP: 1,077 km.'},
{c:"Ch.12 Geography",q:'Narmada nadi MP mein kitni lambai mein behti hai?',o:['877 km','977 km','1,077 km','1,177 km'],a:2,n:'Narmada flows 1,077 km within MP.'},
{c:"Ch.12 Geography",q:'Narmada nadi kis samudra mein girti hai?',o:['Bay of Bengal','Arabian Sea','Indian Ocean','Lakshadweep Sea'],a:1,n:'Narmada flows WEST into Arabian Sea.'},
{c:"Ch.12 Geography",q:'Chambal nadi ka udgam kahan hai?',o:['Betul','Amarkantak','Janapav Hill Mhow Indore','Kakra Bardi'],a:2,n:'Chambal from Janapav Hill, Mhow, Indore.'},
{c:"Ch.12 Geography",q:'Chambal nadi kaunsi nadi ki sahayak hai?',o:['Narmada','Tapti','Yamuna','Ganga'],a:2,n:'Chambal = tributary of Yamuna.'},
{c:"Ch.12 Geography",q:'Chambal nadi MP mein kitni lambai ki hai?',o:['120 km','220 km','320 km','420 km'],a:2,n:'Chambal flows 320 km within MP.'},
{c:"Ch.12 Geography",q:'Betwa nadi ka udgam kahan hai?',o:['Pachmarhi','Kumra village Raisen','Amarkantak','Betul'],a:1,n:'Betwa from Kumra, Raisen. Total 590 km.'},
{c:"Ch.12 Geography",q:'Betwa nadi kahan Yamuna mein milti hai?',o:['Allahabad','Hamirpur UP','Kanpur','Mathura'],a:1,n:'Betwa meets Yamuna at Hamirpur, UP.'},
{c:"Ch.12 Geography",q:'Ken nadi ka udgam kahan hai?',o:['Ahirgawan Jabalpur','Pachmarhi','Amarkantak','Betul'],a:0,n:'Ken from Ahirgawan, Jabalpur. 427 km.'},
{c:"Ch.12 Geography",q:'Tapti nadi ka udgam kahan hai?',o:['Pachmarhi','Betul (Multai)','Amarkantak','Janapav Hill'],a:1,n:'Tapti from Multai, Betul. 724 km. Flows WEST.'},
{c:"Ch.12 Geography",q:'Shipra nadi ka udgam kahan hai?',o:['Amarkantak','Pachmarhi','Kakra Bardi Mountain Indore','Betul'],a:2,n:'Shipra from Kakra Bardi Mountain, Indore.'},
{c:"Ch.12 Geography",q:'Shipra nadi kaunsi nadi ki sahayak hai?',o:['Narmada','Betwa','Chambal','Tapti'],a:2,n:'Shipra is a tributary of Chambal.'},
{c:"Ch.12 Geography",q:'Shipra nadi ko kya kaha jaata hai?',o:['Lifeline of MP','Ganga of Malwa','Mother river','Sacred river of Ujjain'],a:1,n:"Shipra = 'Ganga of Malwa.'"},
{c:"Ch.12 Geography",q:'Amarkantak se kaun si nadiyan nikalti hain?',o:['Narmada only','Narmada & Sone','Narmada, Sone & Johila','Chambal & Narmada'],a:2,n:'3 rivers from Amarkantak: Narmada + Sone + Johila. ★★'},
{c:"Ch.12 Geography",q:'Sone nadi kaunse basin mein hai?',o:['Narmada basin','Yamuna basin','Ganga basin','Godavari basin'],a:2,n:'Sone = Ganga basin. Goes NE to Bihar then joins Ganga.'},
{c:"Ch.12 Geography",q:'Mahi nadi ki kaunsi visheshata hai?',o:['Sabse lambi','2 baar Kark Rekha cross karti hai','Sabse saaf','Sabse gahri'],a:1,n:'Mahi crosses Tropic of Cancer TWICE.'},
{c:"Ch.12 Geography",q:'Mahi nadi ka udgam kahan hai?',o:['Dhar/Jhabua district','Betul','Amarkantak','Pachmarhi'],a:0,n:'Mahi originates from Dhar/Jhabua.'},
{c:"Ch.12 Geography",q:'Wainganga nadi kaunse basin mein hai?',o:['Narmada basin','Yamuna basin','Ganga basin','Godavari basin'],a:3,n:'Wainganga = Godavari basin. Goes into Maharashtra.'},
{c:"Ch.12 Geography",q:'Wainganga nadi ka udgam kahan hai?',o:['Balaghat','Mandla','Seoni','Dindori'],a:2,n:'Wainganga originates in Seoni.'},
{c:"Ch.12 Geography",q:'Kaali Mitti (Black Soil) MP mein kahan payi jaati hai?',o:['Bundelkhand','Baghelkhand','Malwa Plateau & Narmada Valley','Eastern MP'],a:2,n:'Kaali Mitti = Malwa Plateau & Narmada Valley.'},
{c:"Ch.12 Geography",q:'Laal Mitti (Red Soil) kahan payi jaati hai?',o:['Malwa','Chambal','Baghelkhand & Bundelkhand','Narmada Valley'],a:2,n:'Red soil = Baghelkhand & Bundelkhand.'},
{c:"Ch.12 Geography",q:'Alluvial soil MP mein kahan hai?',o:['Malwa','Chambal & Narmada floodplains','Eastern MP','Northern MP'],a:1,n:'Alluvial soil in Chambal & Narmada floodplains.'},
{c:"Ch.12 Geography",q:'Laterite soil kahan payi jaati hai?',o:['Malwa','Gwalior-Chambal','Eastern MP — Balaghat, Mandla','Narmada Valley'],a:2,n:'Laterite soil in eastern MP.'},
{c:"Ch.12 Geography",q:'MP mein UNESCO sites kitni hain?',o:['2','3','4','5'],a:1,n:'3 UNESCO: Khajuraho 1986, Sanchi 1989, Bhimbetka 2003.'},
{c:"Ch.12 Geography",q:'Khajuraho ko UNESCO kab mila?',o:['1982','1986','1989','2003'],a:1,n:'Khajuraho UNESCO = 1986.'},
{c:"Ch.12 Geography",q:'Sanchi ko UNESCO kab mila?',o:['1986','1989','1993','2003'],a:1,n:'Sanchi UNESCO = 1989.'},
{c:"Ch.12 Geography",q:'Bhimbetka ko UNESCO kab mila?',o:['1999','2001','2003','2005'],a:2,n:'Bhimbetka UNESCO = 2003.'},
{c:"Ch.12 Geography",q:'Bhimbetka ki rock paintings kitni purani hain?',o:['5,000+ years','8,000+ years','10,000+ years','15,000+ years'],a:2,n:'Bhimbetka paintings = 10,000+ years old.'},
{c:"Ch.12 Geography",q:'Vindhya Range kahan sthit hai?',o:['Northern MP','Central MP (N-S divide)','Southern MP','Eastern MP'],a:1,n:'Vindhya Range runs through central MP.'},
{c:"Ch.12 Geography",q:'MP ke pramukh khanijon mein slate ka utpaadan kahan hota hai?',o:['Panna','Balaghat','Mandsaur','Singrauli'],a:2,n:'Mandsaur = only slate producer in India.'},
{c:"Ch.12 Geography",q:'Narmada nadi ki kitni sahayak (tributary) nadiyan hain?',o:['21','31','41','51'],a:2,n:'Narmada has 41 tributaries.'},
{c:"Ch.13 Economy",q:'India mein soyabean ka #1 utpadak rajya kaun sa hai?',o:['Maharashtra','Rajasthan','Madhya Pradesh','Karnataka'],a:2,n:"MP = 55–60% of India's soyabean. State crop."},
{c:"Ch.13 Economy",q:'MP ka rajya fasal kaun si hai?',o:['Wheat','Rice','Soyabean','Cotton'],a:2,n:'Soyabean = state crop of MP.'},
{c:"Ch.13 Economy",q:'MP ki bijli utpaadan kshamata (Mar 2024) kitni hai?',o:['17,108 MW','22,108 MW','27,108 MW','32,108 MW'],a:2,n:'27,108.55 MW.'},
{c:"Ch.13 Economy",q:'MP mein kitne pratishat grihasthon mein bijli hai?',o:['87%','92%','95%','97%'],a:3,n:'97% households.'},
{c:"Ch.13 Economy",q:'NTPC Vindhyachal India ka sabse bada thermal plant hai — kahan?',o:['Rewa','Satna','Singrauli','Shahdol'],a:2,n:'NTPC Vindhyachal (4,760 MW) in Singrauli.'},
{c:"Ch.13 Economy",q:'Rewa Solar Park kahan hai?',o:['Gurh Tehsil, Rewa','Satna','Shahdol','Sidhi'],a:0,n:'750 MW Ultra Mega Solar Park at Gurh Tehsil, Rewa.'},
{c:"Ch.13 Economy",q:'Rewa Solar Park kab commissioned hua?',o:['2018','2019','2020','2021'],a:2,n:'Rewa Solar Park commissioned 2020.'},
{c:"Ch.13 Economy",q:'Rewa Solar Park se kaun sa project bijli leta hai?',o:['Delhi Airport','Delhi Metro','Delhi Jal Board','Delhi Secretariat'],a:1,n:'Powers Delhi Metro.'},
{c:"Ch.13 Economy",q:'IIT Indore kab sthapit hua?',o:['2004','2007','2009','2012'],a:2,n:'IIT Indore = 2009, Simrol campus.'},
{c:"Ch.13 Economy",q:'IIM Indore kab sthapit hua?',o:['1990','1993','1996','2000'],a:2,n:'IIM Indore = 1996.'},
{c:"Ch.13 Economy",q:'AIIMS Bhopal kab sthapit hua?',o:['2010','2012','2014','2016'],a:1,n:'AIIMS Bhopal = 2012.'},
{c:"Ch.13 Economy",q:'Swachh Survekshan 2024 mein Indore kaun si jagah raha?',o:['5th consecutive','6th consecutive','7th consecutive','8th consecutive'],a:3,n:'Indore = Cleanest City 8 consecutive times.'},
{c:"Ch.13 Economy",q:'India mein Currency Note Press kitne hain aur MP mein kahan?',o:['2 — Bhopal','3 — Indore','4 — Dewas','5 — Ujjain'],a:2,n:'4 presses in India. MP = Dewas.'},
{c:"Ch.13 Economy",q:'Malajkhand copper mine kab inaugurated hua?',o:['1971','1975','1982','1991'],a:2,n:'Inaugurated by Indira Gandhi in 1982.'},
{c:"Ch.13 Economy",q:'Malajkhand copper mine ka sanchaalan kaun karta hai?',o:['NMDC','HCL','SAIL','NALCO'],a:1,n:'HCL (Hindustan Copper Limited).'},
{c:"Ch.13 Economy",q:'India ka sabse bada open-cast copper mine kahan hai?',o:['Rajasthan','Jharkhand','Malajkhand Balaghat MP','Karnataka'],a:2,n:'Malajkhand, Balaghat.'},
{c:"Ch.13 Economy",q:'Forest area mein MP ka India mein rank kya hai?',o:['2nd','3rd','1st','4th'],a:2,n:'1st rank (FSI 2023).',u:'Updated: 3rd → 1st.'},
{c:"Ch.13 Economy",q:'Fiscal Health Index 2025 mein MP ka rank kya hai?',o:['5th','7th','9th','11th'],a:2,n:'Rank 9th (score 42.2).'},
{c:"Ch.13 Economy",q:'NCL (Northern Coalfields Ltd) kahan operate karta hai?',o:['Rewa','Shahdol','Singrauli','Panna'],a:2,n:'NCL in Singrauli coalfield.'},
{c:"Ch.13 Economy",q:'MP ke kaunse shahar Smart Cities Mission mein hain?',o:['5 cities','6 cities','7 cities','8 cities'],a:2,n:'7 Smart Cities: Bhopal, Indore, Gwalior, Jabalpur, Satna, Ujjain, Sagar.'},
{c:"Ch.13 Economy",q:'Bhopal Airport ka naam kya hai?',o:['Devi Ahilyabai Holkar','Raja Bhoj Airport','Rajmata VS Airport','Bhimrao Ambedkar'],a:1,n:'Raja Bhoj Airport, Bhopal.'},
{c:"Ch.13 Economy",q:'Gwalior Airport ka naam kya hai?',o:['Raja Bhoj Airport','Devi Ahilyabai Airport','Rajmata Vijayaraje Scindia Airport','Bhimrao Ambedkar'],a:2,n:'Rajmata Vijayaraje Scindia Airport — largest runway in MP.'},
{c:"Ch.13 Economy",q:'Khajuraho Airport kis cheez ke liye important hai?',o:['International cargo','Tourism connectivity for UNESCO site','Military operations','Defence training'],a:1,n:'Khajuraho Airport = tourism connectivity for UNESCO World Heritage site.'},
{c:"Ch.13 Economy",q:'Mandsaur kis mineral ke liye prasiddh hai?',o:['Diamonds','Copper','Slate pencil (only in India)','Bauxite'],a:2,n:'Mandsaur = only slate pencil producer in India.'},
{c:"Ch.13 Economy",q:'Panna district kisliye prasiddh hai?',o:['Coal mining','Copper mining','Diamond mining (only in India)','Manganese mining'],a:2,n:'Panna = only diamond mining in India (Majhgawan mine, NMDC).'},
{c:"Ch.15 Kya Badla",q:'Old textbook mein 51 jile the — ab (2026) mein kitne?',o:['52','53','54','55'],a:3,n:'55 districts (2013→51, 2018→52, 2023→55).',u:'51 → 55.'},
{c:"Ch.15 Kya Badla",q:'Old textbook mein 16 Nagar Nigam the — ab kitne?',o:['17','18','19','20'],a:1,n:'18 Nagar Nigam.',u:'16 → 18.'},
{c:"Ch.15 Kya Badla",q:'Old textbook mein 371 Tehsilen thin — ab kitni?',o:['390','410','428','450'],a:2,n:'428 tehsils.',u:'371 → 428.'},
{c:"Ch.15 Kya Badla",q:'Old textbook mein 22,816 GP thin — ab kitni?',o:['22,816','~23,043','24,000','25,000'],a:1,n:'~23,043 GP.',u:'22,816 → ~23,043.'},
{c:"Ch.15 Kya Badla",q:'Forest area rank purane notes mein 3rd tha — ab kya hai?',o:['2nd','1st','3rd','4th'],a:1,n:'1st (FSI 2023).',u:'3rd → 1st.'},
{c:"Ch.15 Kya Badla",q:'Rajya Khel ghoshna: purane notes 1981 kehte hain — sahi date?',o:['1 Nov 1981','26 Jan 1972','9 April 2013','15 Aug 2000'],a:2,n:'Malkhamb = 9 April 2013.',u:'NOT 1981.'},
{c:"Ch.15 Kya Badla",q:'Highest peak: purane notes 1,350 m kehte hain — sahi unchai?',o:['1,350 m','1,352 m','1,400 m','1,320 m'],a:1,n:'1,352 m (Dhupgarh).',u:'1,350 → 1,352 m.'},
{c:"Ch.15 Kya Badla",q:'MP ki population rank purane notes mein 2nd thi — ab kya hai?',o:['2nd','3rd','4th','5th'],a:3,n:'5th most populous.',u:'2nd → 5th.'},
{c:"Ch.15 Kya Badla",q:'Old data mein Nagar Panchayat 272 thi — ab kitni?',o:['264','272','280','290'],a:0,n:'264.',u:'272 → 264.'},
{c:"Ch.15 Kya Badla",q:'Old data mein Kul Nagar 476 tha — ab ULB ki sankhya?',o:['380','382','400','420'],a:1,n:'382 ULBs (18+100+264).',u:'476 → 382.'},
{c:"Ch.15 Kya Badla",q:'Old data mein 98 Nagar Palika thin — ab kitni?',o:['99','100','102','105'],a:1,n:'100 Nagar Palika.',u:'98 → 100.'},
{c:"Ch.15 Kya Badla",q:'Old data mein CM Shivraj Singh Chouhan the — ab kaun?',o:['Kamal Nath','Narendra Singh Tomar','Mohan Yadav','VD Sharma'],a:2,n:'Mohan Yadav (BJP, Dec 2023).',u:'Shivraj → Mohan Yadav.'},
{c:"Ch.15 Kya Badla",q:'Old data mein VS 320 seeten thin — ab kitni?',o:['250','230','220','200'],a:1,n:'230 (CG separation 2000).',u:'320 → 230.'},
{c:"Ch.15 Kya Badla",q:'313 Vikas Khanda — 2026 mein kya status hai?',o:['Changed to 350','Changed to 280','CONFIRMED UNCHANGED at 313','Changed to 428'],a:2,n:'313 Vikas Khanda — CONFIRMED unchanged.'},
{c:"Ch.15 Kya Badla",q:'29 Lok Sabha + 11 Rajya Sabha — 2026 mein kya status hai?',o:['Changed','CONFIRMED SAME — 40 total','Increased','Decreased'],a:1,n:'29+11=40 Parliament seats — CONFIRMED SAME.'}
];